name: xga
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - python=3.12
  - conda-forge::astropy
  - tqdm
  - pandas
  - conda-forge::regions
  - conda-forge::fitsio
  - matplotlib
  - scipy
  - conda-forge::pyabel
  - conda-forge::corner
  - conda-forge::emcee
  - conda-forge::tabulate
  - conda-forge::getdist
  - anaconda::pytest
  - anaconda::exceptiongroup
