// ----------------------------------
// XMM-Newton Science Analysis System
// ----------------------------------
//
// ODF Summary File
// By: odfingest(odfingest-3.30) [xmmsas_20141104_1833-14.0.0] on 2020-05-15T09:13:52.000
//
//
// Directory where the ODF constituents were found. This may have to be edited to match the local file system structure.
//
PATH /lustre/scratch/astro/sb765/code/xcs_dr2_tx/xcs3pv3/tx_for_Bulbul_sample/clusters/XMMXCSJ095822.0-110349.6-0.153/0201901401/odf
//
// Observation Record
//
OBSERVATION
0201901401 / Observation Identifier
0809 / Revolution Identifier
2004-05-09T13:00:16.000 / Observation Start Time
2004-05-09T20:20:16.000 / Observation End Time
//
// Number of files in the Observation Summary File, and their names
//
FILES
160 / Number of Files
0809_0201901401_M1U00200AUX.FIT / ODF Constituent
0809_0201901401_M1U00210IME.FIT / ODF Constituent
0809_0201901401_M1U00220IME.FIT / ODF Constituent
0809_0201901401_M1U00230IME.FIT / ODF Constituent
0809_0201901401_M1U00240IME.FIT / ODF Constituent
0809_0201901401_M1U00250IME.FIT / ODF Constituent
0809_0201901401_M1U00260IME.FIT / ODF Constituent
0809_0201901401_M1U00270IME.FIT / ODF Constituent
0809_0201901401_M1X00000HCH.FIT / ODF Constituent
0809_0201901401_M1X00000PEH.FIT / ODF Constituent
0809_0201901401_M2U00200AUX.FIT / ODF Constituent
0809_0201901401_M2U00210IME.FIT / ODF Constituent
0809_0201901401_M2U00220IME.FIT / ODF Constituent
0809_0201901401_M2U00230IME.FIT / ODF Constituent
0809_0201901401_M2U00240IME.FIT / ODF Constituent
0809_0201901401_M2U00250IME.FIT / ODF Constituent
0809_0201901401_M2U00260IME.FIT / ODF Constituent
0809_0201901401_M2U00270IME.FIT / ODF Constituent
0809_0201901401_M2X00000HCH.FIT / ODF Constituent
0809_0201901401_M2X00000PEH.FIT / ODF Constituent
0809_0201901401_OMS00600IMI.FIT / ODF Constituent
0809_0201901401_OMS00600RFX.FIT / ODF Constituent
0809_0201901401_OMS00600THX.FIT / ODF Constituent
0809_0201901401_OMS00600WDX.FIT / ODF Constituent
0809_0201901401_OMS00601IMI.FIT / ODF Constituent
0809_0201901401_OMS00700IMI.FIT / ODF Constituent
0809_0201901401_OMS00700RFX.FIT / ODF Constituent
0809_0201901401_OMS00700WDX.FIT / ODF Constituent
0809_0201901401_OMS00701IMI.FIT / ODF Constituent
0809_0201901401_OMS40000PAX.FIT / ODF Constituent
0809_0201901401_OMS40000RFX.FIT / ODF Constituent
0809_0201901401_OMS40400IMI.FIT / ODF Constituent
0809_0201901401_OMS40400RFX.FIT / ODF Constituent
0809_0201901401_OMS40400THX.FIT / ODF Constituent
0809_0201901401_OMS40400WDX.FIT / ODF Constituent
0809_0201901401_OMS40401IMI.FIT / ODF Constituent
0809_0201901401_OMS40500IMI.FIT / ODF Constituent
0809_0201901401_OMS40500RFX.FIT / ODF Constituent
0809_0201901401_OMS40500WDX.FIT / ODF Constituent
0809_0201901401_OMS40501IMI.FIT / ODF Constituent
0809_0201901401_OMS40600IMI.FIT / ODF Constituent
0809_0201901401_OMS40600RFX.FIT / ODF Constituent
0809_0201901401_OMS40600WDX.FIT / ODF Constituent
0809_0201901401_OMS40601IMI.FIT / ODF Constituent
0809_0201901401_OMS40700IMI.FIT / ODF Constituent
0809_0201901401_OMS40700RFX.FIT / ODF Constituent
0809_0201901401_OMS40700WDX.FIT / ODF Constituent
0809_0201901401_OMS40701IMI.FIT / ODF Constituent
0809_0201901401_OMS40800IMI.FIT / ODF Constituent
0809_0201901401_OMS40800RFX.FIT / ODF Constituent
0809_0201901401_OMS40800WDX.FIT / ODF Constituent
0809_0201901401_OMS40801IMI.FIT / ODF Constituent
0809_0201901401_OMX00000NPH.FIT / ODF Constituent
0809_0201901401_OMX00000PEH.FIT / ODF Constituent
0809_0201901401_PNU00200AUX.FIT / ODF Constituent
0809_0201901401_PNU00200CCX.FIT / ODF Constituent
0809_0201901401_PNU00201HDI.FIT / ODF Constituent
0809_0201901401_PNU00201IME.FIT / ODF Constituent
0809_0201901401_PNU00202HDI.FIT / ODF Constituent
0809_0201901401_PNU00202IME.FIT / ODF Constituent
0809_0201901401_PNU00203HDI.FIT / ODF Constituent
0809_0201901401_PNU00203IME.FIT / ODF Constituent
0809_0201901401_PNU00204HDI.FIT / ODF Constituent
0809_0201901401_PNU00204IME.FIT / ODF Constituent
0809_0201901401_PNU00205HDI.FIT / ODF Constituent
0809_0201901401_PNU00205IME.FIT / ODF Constituent
0809_0201901401_PNU00206HDI.FIT / ODF Constituent
0809_0201901401_PNU00206IME.FIT / ODF Constituent
0809_0201901401_PNU00207HDI.FIT / ODF Constituent
0809_0201901401_PNU00207IME.FIT / ODF Constituent
0809_0201901401_PNU00208HDI.FIT / ODF Constituent
0809_0201901401_PNU00208IME.FIT / ODF Constituent
0809_0201901401_PNU00209HDI.FIT / ODF Constituent
0809_0201901401_PNU00209IME.FIT / ODF Constituent
0809_0201901401_PNU00210HDI.FIT / ODF Constituent
0809_0201901401_PNU00210IME.FIT / ODF Constituent
0809_0201901401_PNU00211HDI.FIT / ODF Constituent
0809_0201901401_PNU00211IME.FIT / ODF Constituent
0809_0201901401_PNU00212HDI.FIT / ODF Constituent
0809_0201901401_PNU00212IME.FIT / ODF Constituent
0809_0201901401_PNU00301DLI.FIT / ODF Constituent
0809_0201901401_PNU00402DLI.FIT / ODF Constituent
0809_0201901401_PNU00503DLI.FIT / ODF Constituent
0809_0201901401_PNU00604DLI.FIT / ODF Constituent
0809_0201901401_PNU00705DLI.FIT / ODF Constituent
0809_0201901401_PNU00806DLI.FIT / ODF Constituent
0809_0201901401_PNU00907DLI.FIT / ODF Constituent
0809_0201901401_PNU01008DLI.FIT / ODF Constituent
0809_0201901401_PNU01109DLI.FIT / ODF Constituent
0809_0201901401_PNU01210DLI.FIT / ODF Constituent
0809_0201901401_PNU01311DLI.FIT / ODF Constituent
0809_0201901401_PNU01412DLI.FIT / ODF Constituent
0809_0201901401_PNX00000HCH.FIT / ODF Constituent
0809_0201901401_PNX00000PAH.FIT / ODF Constituent
0809_0201901401_PNX00000PMH.FIT / ODF Constituent
0809_0201901401_R1S00400AUX.FIT / ODF Constituent
0809_0201901401_R1S00401DII.FIT / ODF Constituent
0809_0201901401_R1S00401SPE.FIT / ODF Constituent
0809_0201901401_R1S00402DII.FIT / ODF Constituent
0809_0201901401_R1S00402SPE.FIT / ODF Constituent
0809_0201901401_R1S00403DII.FIT / ODF Constituent
0809_0201901401_R1S00403SPE.FIT / ODF Constituent
0809_0201901401_R1S00404DII.FIT / ODF Constituent
0809_0201901401_R1S00404SPE.FIT / ODF Constituent
0809_0201901401_R1S00405DII.FIT / ODF Constituent
0809_0201901401_R1S00405SPE.FIT / ODF Constituent
0809_0201901401_R1S00406DII.FIT / ODF Constituent
0809_0201901401_R1S00406SPE.FIT / ODF Constituent
0809_0201901401_R1S00408DII.FIT / ODF Constituent
0809_0201901401_R1S00408SPE.FIT / ODF Constituent
0809_0201901401_R1S00409DII.FIT / ODF Constituent
0809_0201901401_R1S00409SPE.FIT / ODF Constituent
0809_0201901401_R1S90003DII.FIT / ODF Constituent
0809_0201901401_R1S90104DII.FIT / ODF Constituent
0809_0201901401_R1X00000D1H.FIT / ODF Constituent
0809_0201901401_R1X00000D2H.FIT / ODF Constituent
0809_0201901401_R1X00000OFX.FIT / ODF Constituent
0809_0201901401_R1X00000PFH.FIT / ODF Constituent
0809_0201901401_R2S00500AUX.FIT / ODF Constituent
0809_0201901401_R2S00501DII.FIT / ODF Constituent
0809_0201901401_R2S00501SPE.FIT / ODF Constituent
0809_0201901401_R2S00502DII.FIT / ODF Constituent
0809_0201901401_R2S00502SPE.FIT / ODF Constituent
0809_0201901401_R2S00503DII.FIT / ODF Constituent
0809_0201901401_R2S00503SPE.FIT / ODF Constituent
0809_0201901401_R2S00505DII.FIT / ODF Constituent
0809_0201901401_R2S00505SPE.FIT / ODF Constituent
0809_0201901401_R2S00506DII.FIT / ODF Constituent
0809_0201901401_R2S00506SPE.FIT / ODF Constituent
0809_0201901401_R2S00507DII.FIT / ODF Constituent
0809_0201901401_R2S00507SPE.FIT / ODF Constituent
0809_0201901401_R2S00508DII.FIT / ODF Constituent
0809_0201901401_R2S00508SPE.FIT / ODF Constituent
0809_0201901401_R2S00509DII.FIT / ODF Constituent
0809_0201901401_R2S00509SPE.FIT / ODF Constituent
0809_0201901401_R2S90003DII.FIT / ODF Constituent
0809_0201901401_R2S90105DII.FIT / ODF Constituent
0809_0201901401_R2X00000D1H.FIT / ODF Constituent
0809_0201901401_R2X00000D2H.FIT / ODF Constituent
0809_0201901401_R2X00000OFX.FIT / ODF Constituent
0809_0201901401_R2X00000PFH.FIT / ODF Constituent
0809_0201901401_RMX00100ECX.FIT / ODF Constituent
0809_0201901401_RMX00100ESX.FIT / ODF Constituent
0809_0201901401_RMX00200ECX.FIT / ODF Constituent
0809_0201901401_RMX00200ESX.FIT / ODF Constituent
0809_0201901401_SCX00000ATS.FIT / ODF Constituent
0809_0201901401_SCX00000P1S.FIT / ODF Constituent
0809_0201901401_SCX00000P2S.FIT / ODF Constituent
0809_0201901401_SCX00000P3S.FIT / ODF Constituent
0809_0201901401_SCX00000P4S.FIT / ODF Constituent
0809_0201901401_SCX00000P5S.FIT / ODF Constituent
0809_0201901401_SCX00000P6S.FIT / ODF Constituent
0809_0201901401_SCX00000P7S.FIT / ODF Constituent
0809_0201901401_SCX00000P8S.FIT / ODF Constituent
0809_0201901401_SCX00000P9S.FIT / ODF Constituent
0809_0201901401_SCX00000RAS.ASC / ODF Constituent
0809_0201901401_SCX00000ROS.ASC / ODF Constituent
0809_0201901401_SCX00000SUM.SAS / ODF Constituent
0809_0201901401_SCX00000TCS.FIT / ODF Constituent
0809_0201901401_SCX00000TCX.FIT / ODF Constituent
// The CONFIGURATION record was extracted from 0809_0201901401_SCX00000SUM.ASC
CONFIGURATION                                                                   
5
ODF_VERSION = 003 / Qcheck reset ODF version                                   
PRIME_INSTR = E3 / Prime Instrument                                             
// odfingest metadata
ODFINGEST_VERSION = 3.30 / odfingest version
SAS_MANIFEST = xmmsas_20141104_1833-14.0.0 / SAS Manifest
PROCESS_DATE = 2020-05-15T09:13:55.000 / Time and Date when summary file produced
//
// Instrument Record
//
INSTRUMENT
M1
Y / Is this instrument active?
1 / Number of exposures for this instrument
//
// Exposure Record
// Observation Level Exposure Index = 1
// Instrument [M1] Level Exposure Identifier = U002
// Instrument [M1] Level Exposure Index = 1
//
EXPOSURE
002 / Exposure Identifier [also U002]
N / Is this a scheduled exposure?
SCIENCE / Exposure Type
0201901401M1U002 / Commanded Exposure Identifier
0201901401M1U002 / Proposal Exposure Identifier
2004-05-09T16:07:05.000 / Scheduled Start Time
2004-05-09T20:16:21.000 / Scheduled End Time
2004-05-09T16:07:05.000 / Actual Start Time
2004-05-09T20:16:21.000 / Actual End Time
//
// Configuration Record for M1
//
CONFIGURATION EPIC MOS
85 / Number of configuration parameters available
MODE = PrimeFullWindow / Instrument configuration 
CALIBRATION_MODE_1 = PrimeFullWindow / Mode used to calibrate events from CCD 1
CALIBRATION_MODE_2 = PrimeFullWindow / Mode used to calibrate events from CCD 2
CALIBRATION_MODE_3 = PrimeFullWindow / Mode used to calibrate events from CCD 3
CALIBRATION_MODE_4 = PrimeFullWindow / Mode used to calibrate events from CCD 4
CALIBRATION_MODE_5 = PrimeFullWindow / Mode used to calibrate events from CCD 5
CALIBRATION_MODE_6 = PrimeFullWindow / Mode used to calibrate events from CCD 6
CALIBRATION_MODE_7 = PrimeFullWindow / Mode used to calibrate events from CCD 7
DATA_MODE_1 = Imaging / Data mode for CCD 1
DATA_MODE_2 = Imaging / Data mode for CCD 2
DATA_MODE_3 = Imaging / Data mode for CCD 3
DATA_MODE_4 = Imaging / Data mode for CCD 4
DATA_MODE_5 = Imaging / Data mode for CCD 5
DATA_MODE_6 = Imaging / Data mode for CCD 6
DATA_MODE_7 = Imaging / Data mode for CCD 7
FILTER_WHEEL = FILTER A // Name of filter wheel position
FILTER_WHEEL_POSITION = 267 // Hardware filter wheel position
FILTER = Thin1 // Filter
CLOCK_RESET_TIME_COARSE = 121744379 // Coarse component of the clock reset time
CLOCK_RESET_TIME_FINE = 0 // Fine component of the clock reset time
CLOCK_WRAP_AROUND = 32767 // Clock wrap around
MEAN_TEMPERATURE = 34.0323 // Mean temperature
GAIN_CCD_1 = NORMAL // Gain of the read out chain
GAIN_CCD_2 = NORMAL // Gain of the read out chain
GAIN_CCD_3 = NORMAL // Gain of the read out chain
GAIN_CCD_4 = NORMAL // Gain of the read out chain
GAIN_CCD_5 = NORMAL // Gain of the read out chain
GAIN_CCD_6 = NORMAL // Gain of the read out chain
GAIN_CCD_7 = NORMAL // Gain of the read out chain
EDU_0_LOW_THR_1 = 25 // First low threshold of 1st EDU
EDU_0_LOW_THR_2 = 25 // Second low threshold of 1st EDU
EDU_1_LOW_THR_1 = 25 // First low threshold of 2nd EDU
EDU_1_LOW_THR_2 = 25 // Second low threshold of 2nd EDU
EDU_2_LOW_THR_1 = 25 // First low threshold of 3rd EDU
EDU_2_LOW_THR_2 = 25 // Second low threshold of 3rd EDU
EDU_3_LOW_THR_1 = 25 // First low threshold of 4th EDU
EDU_3_LOW_THR_2 = 25 // Second low threshold of 4th EDU
EDU_4_LOW_THR_1 = 25 // First low threshold of 5th EDU
EDU_4_LOW_THR_2 = 25 // Second low threshold of 5th EDU
EDU_5_LOW_THR_1 = 25 // First low threshold of 6th EDU
EDU_5_LOW_THR_2 = 25 // Second low threshold of 6th EDU
EDU_6_LOW_THR_1 = 25 // First low threshold of 7th EDU
EDU_6_LOW_THR_2 = 25 // Second low threshold of 7th EDU
EDU_7_LOW_THR_1 = 25 // First low threshold of 8th EDU
EDU_7_LOW_THR_2 = 25 // Second low threshold of 8th EDU
HBR_0_ACTIVATION_STATUS = 0 // Activation status for HBR 0
HBR_0_PROCESSING_MODE = 0 // Processing mode for HBR 0
HBR_1_ACTIVATION_STATUS = 1 // Activation status for HBR 1
HBR_1_PROCESSING_MODE = 1 // Processing mode for HBR 1
HBR_2_ACTIVATION_STATUS = 1 // Activation status for HBR 2
HBR_2_PROCESSING_MODE = 1 // Processing mode for HBR 2
HBR_3_ACTIVATION_STATUS = 1 // Activation status for HBR 3
HBR_3_PROCESSING_MODE = 1 // Processing mode for HBR 3
HBR_4_ACTIVATION_STATUS = 1 // Activation status for HBR 4
HBR_4_PROCESSING_MODE = 1 // Processing mode for HBR 4
HBR_5_ACTIVATION_STATUS = 1 // Activation status for HBR 5
HBR_5_PROCESSING_MODE = 1 // Processing mode for HBR 5
HBR_6_ACTIVATION_STATUS = 1 // Activation status for HBR 6
HBR_6_PROCESSING_MODE = 1 // Processing mode for HBR 6
HBR_7_ACTIVATION_STATUS = 0 // Activation status for HBR 7
HBR_7_PROCESSING_MODE = 0 // Processing mode for HBR 7
// WARNING: HBR_PATTERN_REFERENCE_0 not found
HBR_PATTERN_REFERENCE_0= Unknown // Pattern reference for HBR 0
// WARNING: HBR_LOW_THR_0 not found
HBR_LOW_THR_0= Unknown // Low threshold for HBR 0
// WARNING: HBR_HIG_THR_0 not found
HBR_HIG_THR_0= Unknown // High threshold for HBR 0
// WARNING: HBR_PATTERN_REFERENCE_1 not found
HBR_PATTERN_REFERENCE_1= Unknown // Pattern reference for HBR 1
// WARNING: HBR_LOW_THR_1 not found
HBR_LOW_THR_1= Unknown // Low threshold for HBR 1
// WARNING: HBR_HIG_THR_1 not found
HBR_HIG_THR_1= Unknown // High threshold for HBR 1
// WARNING: HBR_PATTERN_REFERENCE_2 not found
HBR_PATTERN_REFERENCE_2= Unknown // Pattern reference for HBR 2
// WARNING: HBR_LOW_THR_2 not found
HBR_LOW_THR_2= Unknown // Low threshold for HBR 2
// WARNING: HBR_HIG_THR_2 not found
HBR_HIG_THR_2= Unknown // High threshold for HBR 2
// WARNING: HBR_PATTERN_REFERENCE_3 not found
HBR_PATTERN_REFERENCE_3= Unknown // Pattern reference for HBR 3
// WARNING: HBR_LOW_THR_3 not found
HBR_LOW_THR_3= Unknown // Low threshold for HBR 3
// WARNING: HBR_HIG_THR_3 not found
HBR_HIG_THR_3= Unknown // High threshold for HBR 3
// WARNING: HBR_PATTERN_REFERENCE_4 not found
HBR_PATTERN_REFERENCE_4= Unknown // Pattern reference for HBR 4
// WARNING: HBR_LOW_THR_4 not found
HBR_LOW_THR_4= Unknown // Low threshold for HBR 4
// WARNING: HBR_HIG_THR_4 not found
HBR_HIG_THR_4= Unknown // High threshold for HBR 4
// WARNING: HBR_PATTERN_REFERENCE_5 not found
HBR_PATTERN_REFERENCE_5= Unknown // Pattern reference for HBR 5
// WARNING: HBR_LOW_THR_5 not found
HBR_LOW_THR_5= Unknown // Low threshold for HBR 5
// WARNING: HBR_HIG_THR_5 not found
HBR_HIG_THR_5= Unknown // High threshold for HBR 5
// WARNING: HBR_PATTERN_REFERENCE_6 not found
HBR_PATTERN_REFERENCE_6= Unknown // Pattern reference for HBR 6
// WARNING: HBR_LOW_THR_6 not found
HBR_LOW_THR_6= Unknown // Low threshold for HBR 6
// WARNING: HBR_HIG_THR_6 not found
HBR_HIG_THR_6= Unknown // High threshold for HBR 6
// WARNING: HBR_PATTERN_REFERENCE_7 not found
HBR_PATTERN_REFERENCE_7= Unknown // Pattern reference for HBR 7
// WARNING: HBR_LOW_THR_7 not found
HBR_LOW_THR_7= Unknown // Low threshold for HBR 7
// WARNING: HBR_HIG_THR_7 not found
HBR_HIG_THR_7= Unknown // High threshold for HBR 7
//
// Instrument Record
//
INSTRUMENT
M2
Y / Is this instrument active?
1 / Number of exposures for this instrument
//
// Exposure Record
// Observation Level Exposure Index = 2
// Instrument [M2] Level Exposure Identifier = U002
// Instrument [M2] Level Exposure Index = 1
//
EXPOSURE
002 / Exposure Identifier [also U002]
N / Is this a scheduled exposure?
SCIENCE / Exposure Type
0201901401M2U002 / Commanded Exposure Identifier
0201901401M2U002 / Proposal Exposure Identifier
2004-05-09T16:07:07.000 / Scheduled Start Time
2004-05-09T20:16:25.000 / Scheduled End Time
2004-05-09T16:07:07.000 / Actual Start Time
2004-05-09T20:16:25.000 / Actual End Time
//
// Configuration Record for M2
//
CONFIGURATION EPIC MOS
85 / Number of configuration parameters available
MODE = PrimeFullWindow / Instrument configuration 
CALIBRATION_MODE_1 = PrimeFullWindow / Mode used to calibrate events from CCD 1
CALIBRATION_MODE_2 = PrimeFullWindow / Mode used to calibrate events from CCD 2
CALIBRATION_MODE_3 = PrimeFullWindow / Mode used to calibrate events from CCD 3
CALIBRATION_MODE_4 = PrimeFullWindow / Mode used to calibrate events from CCD 4
CALIBRATION_MODE_5 = PrimeFullWindow / Mode used to calibrate events from CCD 5
CALIBRATION_MODE_6 = PrimeFullWindow / Mode used to calibrate events from CCD 6
CALIBRATION_MODE_7 = PrimeFullWindow / Mode used to calibrate events from CCD 7
DATA_MODE_1 = Imaging / Data mode for CCD 1
DATA_MODE_2 = Imaging / Data mode for CCD 2
DATA_MODE_3 = Imaging / Data mode for CCD 3
DATA_MODE_4 = Imaging / Data mode for CCD 4
DATA_MODE_5 = Imaging / Data mode for CCD 5
DATA_MODE_6 = Imaging / Data mode for CCD 6
DATA_MODE_7 = Imaging / Data mode for CCD 7
FILTER_WHEEL = FILTER A // Name of filter wheel position
FILTER_WHEEL_POSITION = 266 // Hardware filter wheel position
FILTER = Thin1 // Filter
CLOCK_RESET_TIME_COARSE = 121744381 // Coarse component of the clock reset time
CLOCK_RESET_TIME_FINE = 0 // Fine component of the clock reset time
CLOCK_WRAP_AROUND = 32767 // Clock wrap around
MEAN_TEMPERATURE = 30.6404 // Mean temperature
GAIN_CCD_1 = NORMAL // Gain of the read out chain
GAIN_CCD_2 = NORMAL // Gain of the read out chain
GAIN_CCD_3 = NORMAL // Gain of the read out chain
GAIN_CCD_4 = NORMAL // Gain of the read out chain
GAIN_CCD_5 = NORMAL // Gain of the read out chain
GAIN_CCD_6 = NORMAL // Gain of the read out chain
GAIN_CCD_7 = NORMAL // Gain of the read out chain
EDU_0_LOW_THR_1 = 25 // First low threshold of 1st EDU
EDU_0_LOW_THR_2 = 25 // Second low threshold of 1st EDU
EDU_1_LOW_THR_1 = 25 // First low threshold of 2nd EDU
EDU_1_LOW_THR_2 = 25 // Second low threshold of 2nd EDU
EDU_2_LOW_THR_1 = 25 // First low threshold of 3rd EDU
EDU_2_LOW_THR_2 = 25 // Second low threshold of 3rd EDU
EDU_3_LOW_THR_1 = 25 // First low threshold of 4th EDU
EDU_3_LOW_THR_2 = 25 // Second low threshold of 4th EDU
EDU_4_LOW_THR_1 = 25 // First low threshold of 5th EDU
EDU_4_LOW_THR_2 = 25 // Second low threshold of 5th EDU
EDU_5_LOW_THR_1 = 25 // First low threshold of 6th EDU
EDU_5_LOW_THR_2 = 25 // Second low threshold of 6th EDU
EDU_6_LOW_THR_1 = 25 // First low threshold of 7th EDU
EDU_6_LOW_THR_2 = 25 // Second low threshold of 7th EDU
EDU_7_LOW_THR_1 = 25 // First low threshold of 8th EDU
EDU_7_LOW_THR_2 = 25 // Second low threshold of 8th EDU
HBR_0_ACTIVATION_STATUS = 0 // Activation status for HBR 0
HBR_0_PROCESSING_MODE = 0 // Processing mode for HBR 0
HBR_1_ACTIVATION_STATUS = 1 // Activation status for HBR 1
HBR_1_PROCESSING_MODE = 1 // Processing mode for HBR 1
HBR_2_ACTIVATION_STATUS = 1 // Activation status for HBR 2
HBR_2_PROCESSING_MODE = 1 // Processing mode for HBR 2
HBR_3_ACTIVATION_STATUS = 1 // Activation status for HBR 3
HBR_3_PROCESSING_MODE = 1 // Processing mode for HBR 3
HBR_4_ACTIVATION_STATUS = 1 // Activation status for HBR 4
HBR_4_PROCESSING_MODE = 1 // Processing mode for HBR 4
HBR_5_ACTIVATION_STATUS = 1 // Activation status for HBR 5
HBR_5_PROCESSING_MODE = 1 // Processing mode for HBR 5
HBR_6_ACTIVATION_STATUS = 1 // Activation status for HBR 6
HBR_6_PROCESSING_MODE = 1 // Processing mode for HBR 6
HBR_7_ACTIVATION_STATUS = 0 // Activation status for HBR 7
HBR_7_PROCESSING_MODE = 0 // Processing mode for HBR 7
// WARNING: HBR_PATTERN_REFERENCE_0 not found
HBR_PATTERN_REFERENCE_0= Unknown // Pattern reference for HBR 0
// WARNING: HBR_LOW_THR_0 not found
HBR_LOW_THR_0= Unknown // Low threshold for HBR 0
// WARNING: HBR_HIG_THR_0 not found
HBR_HIG_THR_0= Unknown // High threshold for HBR 0
// WARNING: HBR_PATTERN_REFERENCE_1 not found
HBR_PATTERN_REFERENCE_1= Unknown // Pattern reference for HBR 1
// WARNING: HBR_LOW_THR_1 not found
HBR_LOW_THR_1= Unknown // Low threshold for HBR 1
// WARNING: HBR_HIG_THR_1 not found
HBR_HIG_THR_1= Unknown // High threshold for HBR 1
// WARNING: HBR_PATTERN_REFERENCE_2 not found
HBR_PATTERN_REFERENCE_2= Unknown // Pattern reference for HBR 2
// WARNING: HBR_LOW_THR_2 not found
HBR_LOW_THR_2= Unknown // Low threshold for HBR 2
// WARNING: HBR_HIG_THR_2 not found
HBR_HIG_THR_2= Unknown // High threshold for HBR 2
// WARNING: HBR_PATTERN_REFERENCE_3 not found
HBR_PATTERN_REFERENCE_3= Unknown // Pattern reference for HBR 3
// WARNING: HBR_LOW_THR_3 not found
HBR_LOW_THR_3= Unknown // Low threshold for HBR 3
// WARNING: HBR_HIG_THR_3 not found
HBR_HIG_THR_3= Unknown // High threshold for HBR 3
// WARNING: HBR_PATTERN_REFERENCE_4 not found
HBR_PATTERN_REFERENCE_4= Unknown // Pattern reference for HBR 4
// WARNING: HBR_LOW_THR_4 not found
HBR_LOW_THR_4= Unknown // Low threshold for HBR 4
// WARNING: HBR_HIG_THR_4 not found
HBR_HIG_THR_4= Unknown // High threshold for HBR 4
// WARNING: HBR_PATTERN_REFERENCE_5 not found
HBR_PATTERN_REFERENCE_5= Unknown // Pattern reference for HBR 5
// WARNING: HBR_LOW_THR_5 not found
HBR_LOW_THR_5= Unknown // Low threshold for HBR 5
// WARNING: HBR_HIG_THR_5 not found
HBR_HIG_THR_5= Unknown // High threshold for HBR 5
// WARNING: HBR_PATTERN_REFERENCE_6 not found
HBR_PATTERN_REFERENCE_6= Unknown // Pattern reference for HBR 6
// WARNING: HBR_LOW_THR_6 not found
HBR_LOW_THR_6= Unknown // Low threshold for HBR 6
// WARNING: HBR_HIG_THR_6 not found
HBR_HIG_THR_6= Unknown // High threshold for HBR 6
// WARNING: HBR_PATTERN_REFERENCE_7 not found
HBR_PATTERN_REFERENCE_7= Unknown // Pattern reference for HBR 7
// WARNING: HBR_LOW_THR_7 not found
HBR_LOW_THR_7= Unknown // Low threshold for HBR 7
// WARNING: HBR_HIG_THR_7 not found
HBR_HIG_THR_7= Unknown // High threshold for HBR 7
//
// Instrument Record
//
INSTRUMENT
R1
Y / Is this instrument active?
3 / Number of exposures for this instrument
//
// Exposure Record
// Observation Level Exposure Index = 3
// Instrument [R1] Level Exposure Identifier = S004
// Instrument [R1] Level Exposure Index = 1
//
EXPOSURE
004 / Exposure Identifier [also S004]
Y / Is this a scheduled exposure?
SCIENCE / Exposure Type
0201901401R1S004 / Commanded Exposure Identifier
0201901401R1S004 / Proposal Exposure Identifier
2004-05-09T13:32:28.000 / Scheduled Start Time
2004-05-09T20:20:12.000 / Scheduled End Time
2004-05-09T13:32:28.000 / Actual Start Time
2004-05-09T20:20:12.000 / Actual End Time
//
// Configuration Record for R1
//
CONFIGURATION RGS
111 / Number of configuration parameters available
MODE = UNDEFINED / Instrument configuration 
PACKING_SCHEME = PACKED // Packing scheme
CCD_1_ACCEPT_THR_C = 200 // Acceptance threshold side C for CCD 1
CCD_1_ACCEPT_THR_D = 225 // Acceptance threshold side D for CCD 1
CCD_1_UPPER_THR_C = 2600 // Upper threshold side C for CCD 1
CCD_1_UPPER_THR_D = 2600 // Acceptance threshold side D for CCD 1
CCD_2_ACCEPT_THR_C = 220 // Acceptance threshold side C for CCD 2
CCD_2_ACCEPT_THR_D = 245 // Acceptance threshold side D for CCD 2
CCD_2_UPPER_THR_C = 2600 // Upper threshold side C for CCD 2
CCD_2_UPPER_THR_D = 2600 // Acceptance threshold side D for CCD 2
CCD_3_ACCEPT_THR_C = 240 // Acceptance threshold side C for CCD 3
CCD_3_ACCEPT_THR_D = 265 // Acceptance threshold side D for CCD 3
CCD_3_UPPER_THR_C = 3100 // Upper threshold side C for CCD 3
CCD_3_UPPER_THR_D = 3100 // Acceptance threshold side D for CCD 3
CCD_4_ACCEPT_THR_C = 270 // Acceptance threshold side C for CCD 4
CCD_4_ACCEPT_THR_D = 305 // Acceptance threshold side D for CCD 4
CCD_4_UPPER_THR_C = 3100 // Upper threshold side C for CCD 4
CCD_4_UPPER_THR_D = 3100 // Acceptance threshold side D for CCD 4
CCD_5_ACCEPT_THR_C = 300 // Acceptance threshold side C for CCD 5
CCD_5_ACCEPT_THR_D = 325 // Acceptance threshold side D for CCD 5
CCD_5_UPPER_THR_C = 3100 // Upper threshold side C for CCD 5
CCD_5_UPPER_THR_D = 3100 // Acceptance threshold side D for CCD 5
CCD_6_ACCEPT_THR_C = 350 // Acceptance threshold side C for CCD 6
CCD_6_ACCEPT_THR_D = 375 // Acceptance threshold side D for CCD 6
CCD_6_UPPER_THR_C = 3100 // Upper threshold side C for CCD 6
CCD_6_UPPER_THR_D = 3100 // Acceptance threshold side D for CCD 6
CCD_7_ACCEPT_THR_C = 4000 // Acceptance threshold side C for CCD 7
CCD_7_ACCEPT_THR_D = 4000 // Acceptance threshold side D for CCD 7
CCD_7_UPPER_THR_C = 3600 // Upper threshold side C for CCD 7
CCD_7_UPPER_THR_D = 3600 // Acceptance threshold side D for CCD 7
CCD_8_ACCEPT_THR_C = 300 // Acceptance threshold side C for CCD 8
CCD_8_ACCEPT_THR_D = 500 // Acceptance threshold side D for CCD 8
CCD_8_UPPER_THR_C = 3600 // Upper threshold side C for CCD 8
CCD_8_UPPER_THR_D = 3600 // Acceptance threshold side D for CCD 8
CCD_9_ACCEPT_THR_C = 600 // Acceptance threshold side C for CCD 9
CCD_9_ACCEPT_THR_D = 625 // Acceptance threshold side D for CCD 9
CCD_9_UPPER_THR_C = 3600 // Upper threshold side C for CCD 9
CCD_9_UPPER_THR_D = 3600 // Acceptance threshold side D for CCD 9
NUMBER_OF_SLOTS = 8 // Number of readout slots
CCD_INDEX_1 = 1 // CCD read out in the 1st slot
CCD_1_OCB = 3 // On-chip binning factor for the CCD read out in the 1st slot
CCD_1_NODES = 3 // Read-out nodes used fot the CCD read out in the 1st slot
CCD_1_REJECT_THR_C = 175 // Rejection threshold side C for the CCD read out in the 1st slot
CCD_1_REJECT_THR_D = 200 // Rejection threshold side D for the CCD read out in the 1st slot
CCD_1_CSG_PATTERN = 6 // CCD read out in the 1st slot
CCD_INDEX_2 = 2 // CCD read out in the 2nd slot
CCD_2_OCB = 3 // On-chip binning factor for the CCD read out in the 2nd slot
CCD_2_NODES = 3 // Read-out nodes used fot the CCD read out in the 2nd slot
CCD_2_REJECT_THR_C = 175 // Rejection threshold side C for the CCD read out in the 2nd slot
CCD_2_REJECT_THR_D = 200 // Rejection threshold side D for the CCD read out in the 2nd slot
CCD_2_CSG_PATTERN = 7 // CCD read out in the 2nd slot
CCD_INDEX_3 = 3 // CCD read out in the 3rd slot
CCD_3_OCB = 3 // On-chip binning factor for the CCD read out in the 3rd slot
CCD_3_NODES = 3 // Read-out nodes used fot the CCD read out in the 3rd slot
CCD_3_REJECT_THR_C = 175 // Rejection threshold side C for the CCD read out in the 3rd slot
CCD_3_REJECT_THR_D = 200 // Rejection threshold side D for the CCD read out in the 3rd slot
CCD_3_CSG_PATTERN = 6 // CCD read out in the 3rd slot
CCD_INDEX_4 = 4 // CCD read out in the 4th slot
CCD_4_OCB = 3 // On-chip binning factor for the CCD read out in the 4th slot
CCD_4_NODES = 3 // Read-out nodes used fot the CCD read out in the 4th slot
CCD_4_REJECT_THR_C = 175 // Rejection threshold side C for the CCD read out in the 4th slot
CCD_4_REJECT_THR_D = 200 // Rejection threshold side D for the CCD read out in the 4th slot
CCD_4_CSG_PATTERN = 6 // CCD read out in the 4th slot
CCD_INDEX_5 = 5 // CCD read out in the 5th slot
CCD_5_OCB = 3 // On-chip binning factor for the CCD read out in the 5th slot
CCD_5_NODES = 3 // Read-out nodes used fot the CCD read out in the 5th slot
CCD_5_REJECT_THR_C = 175 // Rejection threshold side C for the CCD read out in the 5th slot
CCD_5_REJECT_THR_D = 200 // Rejection threshold side D for the CCD read out in the 5th slot
CCD_5_CSG_PATTERN = 7 // CCD read out in the 5th slot
CCD_INDEX_6 = 6 // CCD read out in the 6th slot
CCD_6_OCB = 3 // On-chip binning factor for the CCD read out in the 6th slot
CCD_6_NODES = 3 // Read-out nodes used fot the CCD read out in the 6th slot
CCD_6_REJECT_THR_C = 175 // Rejection threshold side C for the CCD read out in the 6th slot
CCD_6_REJECT_THR_D = 200 // Rejection threshold side D for the CCD read out in the 6th slot
CCD_6_CSG_PATTERN = 7 // CCD read out in the 6th slot
CCD_INDEX_7 = 8 // CCD read out in the 7th slot
CCD_7_OCB = 3 // On-chip binning factor for the CCD read out in the 7th slot
CCD_7_NODES = 3 // Read-out nodes used fot the CCD read out in the 7th slot
CCD_7_REJECT_THR_C = 175 // Rejection threshold side C for the CCD read out in the 7th slot
CCD_7_REJECT_THR_D = 200 // Rejection threshold side D for the CCD read out in the 7th slot
CCD_7_CSG_PATTERN = 6 // CCD read out in the 7th slot
CCD_INDEX_8 = 9 // CCD read out in the 8th slot
CCD_8_OCB = 3 // On-chip binning factor for the CCD read out in the 8th slot
CCD_8_NODES = 3 // Read-out nodes used fot the CCD read out in the 8th slot
CCD_8_REJECT_THR_C = 175 // Rejection threshold side C for the CCD read out in the 8th slot
CCD_8_REJECT_THR_D = 200 // Rejection threshold side D for the CCD read out in the 8th slot
CCD_8_CSG_PATTERN = 7 // CCD read out in the 8th slot
CCD_INDEX_9 = 0 // CCD read out in the 9th slot
CCD_9_OCB = 3 // On-chip binning factor for the CCD read out in the 9th slot
CCD_9_NODES = 3 // Read-out nodes used fot the CCD read out in the 9th slot
CCD_9_REJECT_THR_C = 0 // Rejection threshold side C for the CCD read out in the 9th slot
CCD_9_REJECT_THR_D = 0 // Rejection threshold side D for the CCD read out in the 9th slot
CCD_9_CSG_PATTERN = 0 // CCD read out in the 9th slot
CCD_INDEX_10 = 0 // CCD read out in the 10th slot
CCD_10_OCB = 3 // On-chip binning factor for the CCD read out in the 10th slot
CCD_10_NODES = 3 // Read-out nodes used fot the CCD read out in the 10th slot
CCD_10_REJECT_THR_C = 0 // Rejection threshold side C for the CCD read out in the 10th slot
CCD_10_REJECT_THR_D = 0 // Rejection threshold side D for the CCD read out in the 10th slot
CCD_10_CSG_PATTERN = 0 // CCD read out in the 10th slot
CCD_INDEX_11 = 0 // CCD read out in the 11th slot
CCD_11_OCB = 3 // On-chip binning factor for the CCD read out in the 11th slot
CCD_11_NODES = 3 // Read-out nodes used fot the CCD read out in the 11th slot
CCD_11_REJECT_THR_C = 0 // Rejection threshold side C for the CCD read out in the 11th slot
CCD_11_REJECT_THR_D = 0 // Rejection threshold side D for the CCD read out in the 11th slot
CCD_11_CSG_PATTERN = 0 // CCD read out in the 11th slot
CCD_INDEX_12 = 0 // CCD read out in the 12th slot
CCD_12_OCB = 3 // On-chip binning factor for the CCD read out in the 12th slot
CCD_12_NODES = 3 // Read-out nodes used fot the CCD read out in the 12th slot
CCD_12_REJECT_THR_C = 0 // Rejection threshold side C for the CCD read out in the 12th slot
CCD_12_REJECT_THR_D = 0 // Rejection threshold side D for the CCD read out in the 12th slot
CCD_12_CSG_PATTERN = 0 // CCD read out in the 12th slot
//
// Exposure Record
// Observation Level Exposure Index = 4
// Instrument [R1] Level Exposure Identifier = S900
// Instrument [R1] Level Exposure Index = 2
//
EXPOSURE
900 / Exposure Identifier [also S900]
Y / Is this a scheduled exposure?
SCIENCE / Exposure Type
0201901401R1S900 / Commanded Exposure Identifier
0201901401R1S900 / Proposal Exposure Identifier
2004-05-09T13:32:28.000 / Scheduled Start Time
2004-05-09T13:32:29.000 / Scheduled End Time
2004-05-09T13:32:28.000 / Actual Start Time
2004-05-09T13:32:29.000 / Actual End Time
//
// Configuration Record for R1
//
CONFIGURATION RGS
113 / Number of configuration parameters available
MODE = Diagnostic3x3 / Instrument configuration 
CALIBRATION_MODE_3 = Diagnostic3x3 / Mode used to calibrate events from CCD 3
DATA_MODE_3 = Diagnostic / Data mode for CCD 3
PACKING_SCHEME = PACKED // Packing scheme
CCD_1_ACCEPT_THR_C = 200 // Acceptance threshold side C for CCD 1
CCD_1_ACCEPT_THR_D = 225 // Acceptance threshold side D for CCD 1
CCD_1_UPPER_THR_C = 2600 // Upper threshold side C for CCD 1
CCD_1_UPPER_THR_D = 2600 // Acceptance threshold side D for CCD 1
CCD_2_ACCEPT_THR_C = 220 // Acceptance threshold side C for CCD 2
CCD_2_ACCEPT_THR_D = 245 // Acceptance threshold side D for CCD 2
CCD_2_UPPER_THR_C = 2600 // Upper threshold side C for CCD 2
CCD_2_UPPER_THR_D = 2600 // Acceptance threshold side D for CCD 2
CCD_3_ACCEPT_THR_C = 240 // Acceptance threshold side C for CCD 3
CCD_3_ACCEPT_THR_D = 265 // Acceptance threshold side D for CCD 3
CCD_3_UPPER_THR_C = 3100 // Upper threshold side C for CCD 3
CCD_3_UPPER_THR_D = 3100 // Acceptance threshold side D for CCD 3
CCD_4_ACCEPT_THR_C = 270 // Acceptance threshold side C for CCD 4
CCD_4_ACCEPT_THR_D = 305 // Acceptance threshold side D for CCD 4
CCD_4_UPPER_THR_C = 3100 // Upper threshold side C for CCD 4
CCD_4_UPPER_THR_D = 3100 // Acceptance threshold side D for CCD 4
CCD_5_ACCEPT_THR_C = 300 // Acceptance threshold side C for CCD 5
CCD_5_ACCEPT_THR_D = 325 // Acceptance threshold side D for CCD 5
CCD_5_UPPER_THR_C = 3100 // Upper threshold side C for CCD 5
CCD_5_UPPER_THR_D = 3100 // Acceptance threshold side D for CCD 5
CCD_6_ACCEPT_THR_C = 350 // Acceptance threshold side C for CCD 6
CCD_6_ACCEPT_THR_D = 375 // Acceptance threshold side D for CCD 6
CCD_6_UPPER_THR_C = 3100 // Upper threshold side C for CCD 6
CCD_6_UPPER_THR_D = 3100 // Acceptance threshold side D for CCD 6
CCD_7_ACCEPT_THR_C = 4000 // Acceptance threshold side C for CCD 7
CCD_7_ACCEPT_THR_D = 4000 // Acceptance threshold side D for CCD 7
CCD_7_UPPER_THR_C = 3600 // Upper threshold side C for CCD 7
CCD_7_UPPER_THR_D = 3600 // Acceptance threshold side D for CCD 7
CCD_8_ACCEPT_THR_C = 300 // Acceptance threshold side C for CCD 8
CCD_8_ACCEPT_THR_D = 500 // Acceptance threshold side D for CCD 8
CCD_8_UPPER_THR_C = 3600 // Upper threshold side C for CCD 8
CCD_8_UPPER_THR_D = 3600 // Acceptance threshold side D for CCD 8
CCD_9_ACCEPT_THR_C = 600 // Acceptance threshold side C for CCD 9
CCD_9_ACCEPT_THR_D = 625 // Acceptance threshold side D for CCD 9
CCD_9_UPPER_THR_C = 3600 // Upper threshold side C for CCD 9
CCD_9_UPPER_THR_D = 3600 // Acceptance threshold side D for CCD 9
NUMBER_OF_SLOTS = 8 // Number of readout slots
CCD_INDEX_1 = 1 // CCD read out in the 1st slot
CCD_1_OCB = 3 // On-chip binning factor for the CCD read out in the 1st slot
CCD_1_NODES = 3 // Read-out nodes used fot the CCD read out in the 1st slot
CCD_1_REJECT_THR_C = 175 // Rejection threshold side C for the CCD read out in the 1st slot
CCD_1_REJECT_THR_D = 200 // Rejection threshold side D for the CCD read out in the 1st slot
CCD_1_CSG_PATTERN = 6 // CCD read out in the 1st slot
CCD_INDEX_2 = 2 // CCD read out in the 2nd slot
CCD_2_OCB = 3 // On-chip binning factor for the CCD read out in the 2nd slot
CCD_2_NODES = 3 // Read-out nodes used fot the CCD read out in the 2nd slot
CCD_2_REJECT_THR_C = 175 // Rejection threshold side C for the CCD read out in the 2nd slot
CCD_2_REJECT_THR_D = 200 // Rejection threshold side D for the CCD read out in the 2nd slot
CCD_2_CSG_PATTERN = 7 // CCD read out in the 2nd slot
CCD_INDEX_3 = 3 // CCD read out in the 3rd slot
CCD_3_OCB = 3 // On-chip binning factor for the CCD read out in the 3rd slot
CCD_3_NODES = 3 // Read-out nodes used fot the CCD read out in the 3rd slot
CCD_3_REJECT_THR_C = 175 // Rejection threshold side C for the CCD read out in the 3rd slot
CCD_3_REJECT_THR_D = 200 // Rejection threshold side D for the CCD read out in the 3rd slot
CCD_3_CSG_PATTERN = 6 // CCD read out in the 3rd slot
CCD_INDEX_4 = 4 // CCD read out in the 4th slot
CCD_4_OCB = 3 // On-chip binning factor for the CCD read out in the 4th slot
CCD_4_NODES = 3 // Read-out nodes used fot the CCD read out in the 4th slot
CCD_4_REJECT_THR_C = 175 // Rejection threshold side C for the CCD read out in the 4th slot
CCD_4_REJECT_THR_D = 200 // Rejection threshold side D for the CCD read out in the 4th slot
CCD_4_CSG_PATTERN = 6 // CCD read out in the 4th slot
CCD_INDEX_5 = 5 // CCD read out in the 5th slot
CCD_5_OCB = 3 // On-chip binning factor for the CCD read out in the 5th slot
CCD_5_NODES = 3 // Read-out nodes used fot the CCD read out in the 5th slot
CCD_5_REJECT_THR_C = 175 // Rejection threshold side C for the CCD read out in the 5th slot
CCD_5_REJECT_THR_D = 200 // Rejection threshold side D for the CCD read out in the 5th slot
CCD_5_CSG_PATTERN = 7 // CCD read out in the 5th slot
CCD_INDEX_6 = 6 // CCD read out in the 6th slot
CCD_6_OCB = 3 // On-chip binning factor for the CCD read out in the 6th slot
CCD_6_NODES = 3 // Read-out nodes used fot the CCD read out in the 6th slot
CCD_6_REJECT_THR_C = 175 // Rejection threshold side C for the CCD read out in the 6th slot
CCD_6_REJECT_THR_D = 200 // Rejection threshold side D for the CCD read out in the 6th slot
CCD_6_CSG_PATTERN = 7 // CCD read out in the 6th slot
CCD_INDEX_7 = 8 // CCD read out in the 7th slot
CCD_7_OCB = 3 // On-chip binning factor for the CCD read out in the 7th slot
CCD_7_NODES = 3 // Read-out nodes used fot the CCD read out in the 7th slot
CCD_7_REJECT_THR_C = 175 // Rejection threshold side C for the CCD read out in the 7th slot
CCD_7_REJECT_THR_D = 200 // Rejection threshold side D for the CCD read out in the 7th slot
CCD_7_CSG_PATTERN = 6 // CCD read out in the 7th slot
CCD_INDEX_8 = 9 // CCD read out in the 8th slot
CCD_8_OCB = 3 // On-chip binning factor for the CCD read out in the 8th slot
CCD_8_NODES = 3 // Read-out nodes used fot the CCD read out in the 8th slot
CCD_8_REJECT_THR_C = 175 // Rejection threshold side C for the CCD read out in the 8th slot
CCD_8_REJECT_THR_D = 200 // Rejection threshold side D for the CCD read out in the 8th slot
CCD_8_CSG_PATTERN = 7 // CCD read out in the 8th slot
CCD_INDEX_9 = 0 // CCD read out in the 9th slot
CCD_9_OCB = 3 // On-chip binning factor for the CCD read out in the 9th slot
CCD_9_NODES = 3 // Read-out nodes used fot the CCD read out in the 9th slot
CCD_9_REJECT_THR_C = 0 // Rejection threshold side C for the CCD read out in the 9th slot
CCD_9_REJECT_THR_D = 0 // Rejection threshold side D for the CCD read out in the 9th slot
CCD_9_CSG_PATTERN = 0 // CCD read out in the 9th slot
CCD_INDEX_10 = 0 // CCD read out in the 10th slot
CCD_10_OCB = 3 // On-chip binning factor for the CCD read out in the 10th slot
CCD_10_NODES = 3 // Read-out nodes used fot the CCD read out in the 10th slot
CCD_10_REJECT_THR_C = 0 // Rejection threshold side C for the CCD read out in the 10th slot
CCD_10_REJECT_THR_D = 0 // Rejection threshold side D for the CCD read out in the 10th slot
CCD_10_CSG_PATTERN = 0 // CCD read out in the 10th slot
CCD_INDEX_11 = 0 // CCD read out in the 11th slot
CCD_11_OCB = 3 // On-chip binning factor for the CCD read out in the 11th slot
CCD_11_NODES = 3 // Read-out nodes used fot the CCD read out in the 11th slot
CCD_11_REJECT_THR_C = 0 // Rejection threshold side C for the CCD read out in the 11th slot
CCD_11_REJECT_THR_D = 0 // Rejection threshold side D for the CCD read out in the 11th slot
CCD_11_CSG_PATTERN = 0 // CCD read out in the 11th slot
CCD_INDEX_12 = 0 // CCD read out in the 12th slot
CCD_12_OCB = 3 // On-chip binning factor for the CCD read out in the 12th slot
CCD_12_NODES = 3 // Read-out nodes used fot the CCD read out in the 12th slot
CCD_12_REJECT_THR_C = 0 // Rejection threshold side C for the CCD read out in the 12th slot
CCD_12_REJECT_THR_D = 0 // Rejection threshold side D for the CCD read out in the 12th slot
CCD_12_CSG_PATTERN = 0 // CCD read out in the 12th slot
//
// Exposure Record
// Observation Level Exposure Index = 5
// Instrument [R1] Level Exposure Identifier = S901
// Instrument [R1] Level Exposure Index = 3
//
EXPOSURE
901 / Exposure Identifier [also S901]
Y / Is this a scheduled exposure?
SCIENCE / Exposure Type
0201901401R1S901 / Commanded Exposure Identifier
0201901401R1S901 / Proposal Exposure Identifier
2004-05-09T13:32:28.000 / Scheduled Start Time
2004-05-09T13:32:29.000 / Scheduled End Time
2004-05-09T13:32:28.000 / Actual Start Time
2004-05-09T13:32:29.000 / Actual End Time
//
// Configuration Record for R1
//
CONFIGURATION RGS
113 / Number of configuration parameters available
MODE = Diagnostic3x3 / Instrument configuration 
CALIBRATION_MODE_4 = Diagnostic3x3 / Mode used to calibrate events from CCD 4
DATA_MODE_4 = Diagnostic / Data mode for CCD 4
PACKING_SCHEME = PACKED // Packing scheme
CCD_1_ACCEPT_THR_C = 200 // Acceptance threshold side C for CCD 1
CCD_1_ACCEPT_THR_D = 225 // Acceptance threshold side D for CCD 1
CCD_1_UPPER_THR_C = 2600 // Upper threshold side C for CCD 1
CCD_1_UPPER_THR_D = 2600 // Acceptance threshold side D for CCD 1
CCD_2_ACCEPT_THR_C = 220 // Acceptance threshold side C for CCD 2
CCD_2_ACCEPT_THR_D = 245 // Acceptance threshold side D for CCD 2
CCD_2_UPPER_THR_C = 2600 // Upper threshold side C for CCD 2
CCD_2_UPPER_THR_D = 2600 // Acceptance threshold side D for CCD 2
CCD_3_ACCEPT_THR_C = 240 // Acceptance threshold side C for CCD 3
CCD_3_ACCEPT_THR_D = 265 // Acceptance threshold side D for CCD 3
CCD_3_UPPER_THR_C = 3100 // Upper threshold side C for CCD 3
CCD_3_UPPER_THR_D = 3100 // Acceptance threshold side D for CCD 3
CCD_4_ACCEPT_THR_C = 270 // Acceptance threshold side C for CCD 4
CCD_4_ACCEPT_THR_D = 305 // Acceptance threshold side D for CCD 4
CCD_4_UPPER_THR_C = 3100 // Upper threshold side C for CCD 4
CCD_4_UPPER_THR_D = 3100 // Acceptance threshold side D for CCD 4
CCD_5_ACCEPT_THR_C = 300 // Acceptance threshold side C for CCD 5
CCD_5_ACCEPT_THR_D = 325 // Acceptance threshold side D for CCD 5
CCD_5_UPPER_THR_C = 3100 // Upper threshold side C for CCD 5
CCD_5_UPPER_THR_D = 3100 // Acceptance threshold side D for CCD 5
CCD_6_ACCEPT_THR_C = 350 // Acceptance threshold side C for CCD 6
CCD_6_ACCEPT_THR_D = 375 // Acceptance threshold side D for CCD 6
CCD_6_UPPER_THR_C = 3100 // Upper threshold side C for CCD 6
CCD_6_UPPER_THR_D = 3100 // Acceptance threshold side D for CCD 6
CCD_7_ACCEPT_THR_C = 4000 // Acceptance threshold side C for CCD 7
CCD_7_ACCEPT_THR_D = 4000 // Acceptance threshold side D for CCD 7
CCD_7_UPPER_THR_C = 3600 // Upper threshold side C for CCD 7
CCD_7_UPPER_THR_D = 3600 // Acceptance threshold side D for CCD 7
CCD_8_ACCEPT_THR_C = 300 // Acceptance threshold side C for CCD 8
CCD_8_ACCEPT_THR_D = 500 // Acceptance threshold side D for CCD 8
CCD_8_UPPER_THR_C = 3600 // Upper threshold side C for CCD 8
CCD_8_UPPER_THR_D = 3600 // Acceptance threshold side D for CCD 8
CCD_9_ACCEPT_THR_C = 600 // Acceptance threshold side C for CCD 9
CCD_9_ACCEPT_THR_D = 625 // Acceptance threshold side D for CCD 9
CCD_9_UPPER_THR_C = 3600 // Upper threshold side C for CCD 9
CCD_9_UPPER_THR_D = 3600 // Acceptance threshold side D for CCD 9
NUMBER_OF_SLOTS = 8 // Number of readout slots
CCD_INDEX_1 = 1 // CCD read out in the 1st slot
CCD_1_OCB = 3 // On-chip binning factor for the CCD read out in the 1st slot
CCD_1_NODES = 3 // Read-out nodes used fot the CCD read out in the 1st slot
CCD_1_REJECT_THR_C = 175 // Rejection threshold side C for the CCD read out in the 1st slot
CCD_1_REJECT_THR_D = 200 // Rejection threshold side D for the CCD read out in the 1st slot
CCD_1_CSG_PATTERN = 6 // CCD read out in the 1st slot
CCD_INDEX_2 = 2 // CCD read out in the 2nd slot
CCD_2_OCB = 3 // On-chip binning factor for the CCD read out in the 2nd slot
CCD_2_NODES = 3 // Read-out nodes used fot the CCD read out in the 2nd slot
CCD_2_REJECT_THR_C = 175 // Rejection threshold side C for the CCD read out in the 2nd slot
CCD_2_REJECT_THR_D = 200 // Rejection threshold side D for the CCD read out in the 2nd slot
CCD_2_CSG_PATTERN = 7 // CCD read out in the 2nd slot
CCD_INDEX_3 = 3 // CCD read out in the 3rd slot
CCD_3_OCB = 3 // On-chip binning factor for the CCD read out in the 3rd slot
CCD_3_NODES = 3 // Read-out nodes used fot the CCD read out in the 3rd slot
CCD_3_REJECT_THR_C = 175 // Rejection threshold side C for the CCD read out in the 3rd slot
CCD_3_REJECT_THR_D = 200 // Rejection threshold side D for the CCD read out in the 3rd slot
CCD_3_CSG_PATTERN = 6 // CCD read out in the 3rd slot
CCD_INDEX_4 = 4 // CCD read out in the 4th slot
CCD_4_OCB = 3 // On-chip binning factor for the CCD read out in the 4th slot
CCD_4_NODES = 3 // Read-out nodes used fot the CCD read out in the 4th slot
CCD_4_REJECT_THR_C = 175 // Rejection threshold side C for the CCD read out in the 4th slot
CCD_4_REJECT_THR_D = 200 // Rejection threshold side D for the CCD read out in the 4th slot
CCD_4_CSG_PATTERN = 6 // CCD read out in the 4th slot
CCD_INDEX_5 = 5 // CCD read out in the 5th slot
CCD_5_OCB = 3 // On-chip binning factor for the CCD read out in the 5th slot
CCD_5_NODES = 3 // Read-out nodes used fot the CCD read out in the 5th slot
CCD_5_REJECT_THR_C = 175 // Rejection threshold side C for the CCD read out in the 5th slot
CCD_5_REJECT_THR_D = 200 // Rejection threshold side D for the CCD read out in the 5th slot
CCD_5_CSG_PATTERN = 7 // CCD read out in the 5th slot
CCD_INDEX_6 = 6 // CCD read out in the 6th slot
CCD_6_OCB = 3 // On-chip binning factor for the CCD read out in the 6th slot
CCD_6_NODES = 3 // Read-out nodes used fot the CCD read out in the 6th slot
CCD_6_REJECT_THR_C = 175 // Rejection threshold side C for the CCD read out in the 6th slot
CCD_6_REJECT_THR_D = 200 // Rejection threshold side D for the CCD read out in the 6th slot
CCD_6_CSG_PATTERN = 7 // CCD read out in the 6th slot
CCD_INDEX_7 = 8 // CCD read out in the 7th slot
CCD_7_OCB = 3 // On-chip binning factor for the CCD read out in the 7th slot
CCD_7_NODES = 3 // Read-out nodes used fot the CCD read out in the 7th slot
CCD_7_REJECT_THR_C = 175 // Rejection threshold side C for the CCD read out in the 7th slot
CCD_7_REJECT_THR_D = 200 // Rejection threshold side D for the CCD read out in the 7th slot
CCD_7_CSG_PATTERN = 6 // CCD read out in the 7th slot
CCD_INDEX_8 = 9 // CCD read out in the 8th slot
CCD_8_OCB = 3 // On-chip binning factor for the CCD read out in the 8th slot
CCD_8_NODES = 3 // Read-out nodes used fot the CCD read out in the 8th slot
CCD_8_REJECT_THR_C = 175 // Rejection threshold side C for the CCD read out in the 8th slot
CCD_8_REJECT_THR_D = 200 // Rejection threshold side D for the CCD read out in the 8th slot
CCD_8_CSG_PATTERN = 7 // CCD read out in the 8th slot
CCD_INDEX_9 = 0 // CCD read out in the 9th slot
CCD_9_OCB = 3 // On-chip binning factor for the CCD read out in the 9th slot
CCD_9_NODES = 3 // Read-out nodes used fot the CCD read out in the 9th slot
CCD_9_REJECT_THR_C = 0 // Rejection threshold side C for the CCD read out in the 9th slot
CCD_9_REJECT_THR_D = 0 // Rejection threshold side D for the CCD read out in the 9th slot
CCD_9_CSG_PATTERN = 0 // CCD read out in the 9th slot
CCD_INDEX_10 = 0 // CCD read out in the 10th slot
CCD_10_OCB = 3 // On-chip binning factor for the CCD read out in the 10th slot
CCD_10_NODES = 3 // Read-out nodes used fot the CCD read out in the 10th slot
CCD_10_REJECT_THR_C = 0 // Rejection threshold side C for the CCD read out in the 10th slot
CCD_10_REJECT_THR_D = 0 // Rejection threshold side D for the CCD read out in the 10th slot
CCD_10_CSG_PATTERN = 0 // CCD read out in the 10th slot
CCD_INDEX_11 = 0 // CCD read out in the 11th slot
CCD_11_OCB = 3 // On-chip binning factor for the CCD read out in the 11th slot
CCD_11_NODES = 3 // Read-out nodes used fot the CCD read out in the 11th slot
CCD_11_REJECT_THR_C = 0 // Rejection threshold side C for the CCD read out in the 11th slot
CCD_11_REJECT_THR_D = 0 // Rejection threshold side D for the CCD read out in the 11th slot
CCD_11_CSG_PATTERN = 0 // CCD read out in the 11th slot
CCD_INDEX_12 = 0 // CCD read out in the 12th slot
CCD_12_OCB = 3 // On-chip binning factor for the CCD read out in the 12th slot
CCD_12_NODES = 3 // Read-out nodes used fot the CCD read out in the 12th slot
CCD_12_REJECT_THR_C = 0 // Rejection threshold side C for the CCD read out in the 12th slot
CCD_12_REJECT_THR_D = 0 // Rejection threshold side D for the CCD read out in the 12th slot
CCD_12_CSG_PATTERN = 0 // CCD read out in the 12th slot
//
// Instrument Record
//
INSTRUMENT
R2
Y / Is this instrument active?
3 / Number of exposures for this instrument
//
// Exposure Record
// Observation Level Exposure Index = 6
// Instrument [R2] Level Exposure Identifier = S005
// Instrument [R2] Level Exposure Index = 1
//
EXPOSURE
005 / Exposure Identifier [also S005]
Y / Is this a scheduled exposure?
SCIENCE / Exposure Type
0201901401R2S005 / Commanded Exposure Identifier
0201901401R2S005 / Proposal Exposure Identifier
2004-05-09T13:34:21.000 / Scheduled Start Time
2004-05-09T20:20:16.000 / Scheduled End Time
2004-05-09T13:34:21.000 / Actual Start Time
2004-05-09T20:20:16.000 / Actual End Time
//
// Configuration Record for R2
//
CONFIGURATION RGS
111 / Number of configuration parameters available
MODE = UNDEFINED / Instrument configuration 
PACKING_SCHEME = PACKED // Packing scheme
CCD_1_ACCEPT_THR_C = 220 // Acceptance threshold side C for CCD 1
CCD_1_ACCEPT_THR_D = 215 // Acceptance threshold side D for CCD 1
CCD_1_UPPER_THR_C = 2600 // Upper threshold side C for CCD 1
CCD_1_UPPER_THR_D = 2600 // Acceptance threshold side D for CCD 1
CCD_2_ACCEPT_THR_C = 220 // Acceptance threshold side C for CCD 2
CCD_2_ACCEPT_THR_D = 245 // Acceptance threshold side D for CCD 2
CCD_2_UPPER_THR_C = 2600 // Upper threshold side C for CCD 2
CCD_2_UPPER_THR_D = 2600 // Acceptance threshold side D for CCD 2
CCD_3_ACCEPT_THR_C = 240 // Acceptance threshold side C for CCD 3
CCD_3_ACCEPT_THR_D = 265 // Acceptance threshold side D for CCD 3
CCD_3_UPPER_THR_C = 3100 // Upper threshold side C for CCD 3
CCD_3_UPPER_THR_D = 3100 // Acceptance threshold side D for CCD 3
CCD_4_ACCEPT_THR_C = 270 // Acceptance threshold side C for CCD 4
CCD_4_ACCEPT_THR_D = 305 // Acceptance threshold side D for CCD 4
CCD_4_UPPER_THR_C = 3100 // Upper threshold side C for CCD 4
CCD_4_UPPER_THR_D = 3100 // Acceptance threshold side D for CCD 4
CCD_5_ACCEPT_THR_C = 300 // Acceptance threshold side C for CCD 5
CCD_5_ACCEPT_THR_D = 325 // Acceptance threshold side D for CCD 5
CCD_5_UPPER_THR_C = 3100 // Upper threshold side C for CCD 5
CCD_5_UPPER_THR_D = 3100 // Acceptance threshold side D for CCD 5
CCD_6_ACCEPT_THR_C = 350 // Acceptance threshold side C for CCD 6
CCD_6_ACCEPT_THR_D = 375 // Acceptance threshold side D for CCD 6
CCD_6_UPPER_THR_C = 3100 // Upper threshold side C for CCD 6
CCD_6_UPPER_THR_D = 3100 // Acceptance threshold side D for CCD 6
CCD_7_ACCEPT_THR_C = 375 // Acceptance threshold side C for CCD 7
CCD_7_ACCEPT_THR_D = 325 // Acceptance threshold side D for CCD 7
CCD_7_UPPER_THR_C = 3600 // Upper threshold side C for CCD 7
CCD_7_UPPER_THR_D = 3600 // Acceptance threshold side D for CCD 7
CCD_8_ACCEPT_THR_C = 300 // Acceptance threshold side C for CCD 8
CCD_8_ACCEPT_THR_D = 500 // Acceptance threshold side D for CCD 8
CCD_8_UPPER_THR_C = 3600 // Upper threshold side C for CCD 8
CCD_8_UPPER_THR_D = 3600 // Acceptance threshold side D for CCD 8
CCD_9_ACCEPT_THR_C = 600 // Acceptance threshold side C for CCD 9
CCD_9_ACCEPT_THR_D = 525 // Acceptance threshold side D for CCD 9
CCD_9_UPPER_THR_C = 3600 // Upper threshold side C for CCD 9
CCD_9_UPPER_THR_D = 3600 // Acceptance threshold side D for CCD 9
NUMBER_OF_SLOTS = 8 // Number of readout slots
CCD_INDEX_1 = 1 // CCD read out in the 1st slot
CCD_1_OCB = 3 // On-chip binning factor for the CCD read out in the 1st slot
CCD_1_NODES = 3 // Read-out nodes used fot the CCD read out in the 1st slot
CCD_1_REJECT_THR_C = 195 // Rejection threshold side C for the CCD read out in the 1st slot
CCD_1_REJECT_THR_D = 190 // Rejection threshold side D for the CCD read out in the 1st slot
CCD_1_CSG_PATTERN = 6 // CCD read out in the 1st slot
CCD_INDEX_2 = 2 // CCD read out in the 2nd slot
CCD_2_OCB = 3 // On-chip binning factor for the CCD read out in the 2nd slot
CCD_2_NODES = 3 // Read-out nodes used fot the CCD read out in the 2nd slot
CCD_2_REJECT_THR_C = 190 // Rejection threshold side C for the CCD read out in the 2nd slot
CCD_2_REJECT_THR_D = 195 // Rejection threshold side D for the CCD read out in the 2nd slot
CCD_2_CSG_PATTERN = 7 // CCD read out in the 2nd slot
CCD_INDEX_3 = 3 // CCD read out in the 3rd slot
CCD_3_OCB = 3 // On-chip binning factor for the CCD read out in the 3rd slot
CCD_3_NODES = 3 // Read-out nodes used fot the CCD read out in the 3rd slot
CCD_3_REJECT_THR_C = 190 // Rejection threshold side C for the CCD read out in the 3rd slot
CCD_3_REJECT_THR_D = 185 // Rejection threshold side D for the CCD read out in the 3rd slot
CCD_3_CSG_PATTERN = 6 // CCD read out in the 3rd slot
CCD_INDEX_4 = 5 // CCD read out in the 4th slot
CCD_4_OCB = 3 // On-chip binning factor for the CCD read out in the 4th slot
CCD_4_NODES = 3 // Read-out nodes used fot the CCD read out in the 4th slot
CCD_4_REJECT_THR_C = 190 // Rejection threshold side C for the CCD read out in the 4th slot
CCD_4_REJECT_THR_D = 200 // Rejection threshold side D for the CCD read out in the 4th slot
CCD_4_CSG_PATTERN = 7 // CCD read out in the 4th slot
CCD_INDEX_5 = 6 // CCD read out in the 5th slot
CCD_5_OCB = 3 // On-chip binning factor for the CCD read out in the 5th slot
CCD_5_NODES = 3 // Read-out nodes used fot the CCD read out in the 5th slot
CCD_5_REJECT_THR_C = 190 // Rejection threshold side C for the CCD read out in the 5th slot
CCD_5_REJECT_THR_D = 190 // Rejection threshold side D for the CCD read out in the 5th slot
CCD_5_CSG_PATTERN = 7 // CCD read out in the 5th slot
CCD_INDEX_6 = 7 // CCD read out in the 6th slot
CCD_6_OCB = 3 // On-chip binning factor for the CCD read out in the 6th slot
CCD_6_NODES = 3 // Read-out nodes used fot the CCD read out in the 6th slot
CCD_6_REJECT_THR_C = 190 // Rejection threshold side C for the CCD read out in the 6th slot
CCD_6_REJECT_THR_D = 200 // Rejection threshold side D for the CCD read out in the 6th slot
CCD_6_CSG_PATTERN = 7 // CCD read out in the 6th slot
CCD_INDEX_7 = 8 // CCD read out in the 7th slot
CCD_7_OCB = 3 // On-chip binning factor for the CCD read out in the 7th slot
CCD_7_NODES = 3 // Read-out nodes used fot the CCD read out in the 7th slot
CCD_7_REJECT_THR_C = 185 // Rejection threshold side C for the CCD read out in the 7th slot
CCD_7_REJECT_THR_D = 200 // Rejection threshold side D for the CCD read out in the 7th slot
CCD_7_CSG_PATTERN = 7 // CCD read out in the 7th slot
CCD_INDEX_8 = 9 // CCD read out in the 8th slot
CCD_8_OCB = 3 // On-chip binning factor for the CCD read out in the 8th slot
CCD_8_NODES = 3 // Read-out nodes used fot the CCD read out in the 8th slot
CCD_8_REJECT_THR_C = 205 // Rejection threshold side C for the CCD read out in the 8th slot
CCD_8_REJECT_THR_D = 200 // Rejection threshold side D for the CCD read out in the 8th slot
CCD_8_CSG_PATTERN = 7 // CCD read out in the 8th slot
CCD_INDEX_9 = 0 // CCD read out in the 9th slot
CCD_9_OCB = 3 // On-chip binning factor for the CCD read out in the 9th slot
CCD_9_NODES = 3 // Read-out nodes used fot the CCD read out in the 9th slot
CCD_9_REJECT_THR_C = 0 // Rejection threshold side C for the CCD read out in the 9th slot
CCD_9_REJECT_THR_D = 0 // Rejection threshold side D for the CCD read out in the 9th slot
CCD_9_CSG_PATTERN = 0 // CCD read out in the 9th slot
CCD_INDEX_10 = 0 // CCD read out in the 10th slot
CCD_10_OCB = 3 // On-chip binning factor for the CCD read out in the 10th slot
CCD_10_NODES = 3 // Read-out nodes used fot the CCD read out in the 10th slot
CCD_10_REJECT_THR_C = 0 // Rejection threshold side C for the CCD read out in the 10th slot
CCD_10_REJECT_THR_D = 0 // Rejection threshold side D for the CCD read out in the 10th slot
CCD_10_CSG_PATTERN = 0 // CCD read out in the 10th slot
CCD_INDEX_11 = 0 // CCD read out in the 11th slot
CCD_11_OCB = 3 // On-chip binning factor for the CCD read out in the 11th slot
CCD_11_NODES = 3 // Read-out nodes used fot the CCD read out in the 11th slot
CCD_11_REJECT_THR_C = 0 // Rejection threshold side C for the CCD read out in the 11th slot
CCD_11_REJECT_THR_D = 0 // Rejection threshold side D for the CCD read out in the 11th slot
CCD_11_CSG_PATTERN = 0 // CCD read out in the 11th slot
CCD_INDEX_12 = 0 // CCD read out in the 12th slot
CCD_12_OCB = 3 // On-chip binning factor for the CCD read out in the 12th slot
CCD_12_NODES = 3 // Read-out nodes used fot the CCD read out in the 12th slot
CCD_12_REJECT_THR_C = 0 // Rejection threshold side C for the CCD read out in the 12th slot
CCD_12_REJECT_THR_D = 0 // Rejection threshold side D for the CCD read out in the 12th slot
CCD_12_CSG_PATTERN = 0 // CCD read out in the 12th slot
//
// Exposure Record
// Observation Level Exposure Index = 7
// Instrument [R2] Level Exposure Identifier = S900
// Instrument [R2] Level Exposure Index = 2
//
EXPOSURE
900 / Exposure Identifier [also S900]
Y / Is this a scheduled exposure?
SCIENCE / Exposure Type
0201901401R2S900 / Commanded Exposure Identifier
0201901401R2S900 / Proposal Exposure Identifier
2004-05-09T13:34:21.000 / Scheduled Start Time
2004-05-09T13:34:22.000 / Scheduled End Time
2004-05-09T13:34:21.000 / Actual Start Time
2004-05-09T13:34:22.000 / Actual End Time
//
// Configuration Record for R2
//
CONFIGURATION RGS
113 / Number of configuration parameters available
MODE = Diagnostic3x3 / Instrument configuration 
CALIBRATION_MODE_3 = Diagnostic3x3 / Mode used to calibrate events from CCD 3
DATA_MODE_3 = Diagnostic / Data mode for CCD 3
PACKING_SCHEME = PACKED // Packing scheme
CCD_1_ACCEPT_THR_C = 220 // Acceptance threshold side C for CCD 1
CCD_1_ACCEPT_THR_D = 215 // Acceptance threshold side D for CCD 1
CCD_1_UPPER_THR_C = 2600 // Upper threshold side C for CCD 1
CCD_1_UPPER_THR_D = 2600 // Acceptance threshold side D for CCD 1
CCD_2_ACCEPT_THR_C = 220 // Acceptance threshold side C for CCD 2
CCD_2_ACCEPT_THR_D = 245 // Acceptance threshold side D for CCD 2
CCD_2_UPPER_THR_C = 2600 // Upper threshold side C for CCD 2
CCD_2_UPPER_THR_D = 2600 // Acceptance threshold side D for CCD 2
CCD_3_ACCEPT_THR_C = 240 // Acceptance threshold side C for CCD 3
CCD_3_ACCEPT_THR_D = 265 // Acceptance threshold side D for CCD 3
CCD_3_UPPER_THR_C = 3100 // Upper threshold side C for CCD 3
CCD_3_UPPER_THR_D = 3100 // Acceptance threshold side D for CCD 3
CCD_4_ACCEPT_THR_C = 270 // Acceptance threshold side C for CCD 4
CCD_4_ACCEPT_THR_D = 305 // Acceptance threshold side D for CCD 4
CCD_4_UPPER_THR_C = 3100 // Upper threshold side C for CCD 4
CCD_4_UPPER_THR_D = 3100 // Acceptance threshold side D for CCD 4
CCD_5_ACCEPT_THR_C = 300 // Acceptance threshold side C for CCD 5
CCD_5_ACCEPT_THR_D = 325 // Acceptance threshold side D for CCD 5
CCD_5_UPPER_THR_C = 3100 // Upper threshold side C for CCD 5
CCD_5_UPPER_THR_D = 3100 // Acceptance threshold side D for CCD 5
CCD_6_ACCEPT_THR_C = 350 // Acceptance threshold side C for CCD 6
CCD_6_ACCEPT_THR_D = 375 // Acceptance threshold side D for CCD 6
CCD_6_UPPER_THR_C = 3100 // Upper threshold side C for CCD 6
CCD_6_UPPER_THR_D = 3100 // Acceptance threshold side D for CCD 6
CCD_7_ACCEPT_THR_C = 375 // Acceptance threshold side C for CCD 7
CCD_7_ACCEPT_THR_D = 325 // Acceptance threshold side D for CCD 7
CCD_7_UPPER_THR_C = 3600 // Upper threshold side C for CCD 7
CCD_7_UPPER_THR_D = 3600 // Acceptance threshold side D for CCD 7
CCD_8_ACCEPT_THR_C = 300 // Acceptance threshold side C for CCD 8
CCD_8_ACCEPT_THR_D = 500 // Acceptance threshold side D for CCD 8
CCD_8_UPPER_THR_C = 3600 // Upper threshold side C for CCD 8
CCD_8_UPPER_THR_D = 3600 // Acceptance threshold side D for CCD 8
CCD_9_ACCEPT_THR_C = 600 // Acceptance threshold side C for CCD 9
CCD_9_ACCEPT_THR_D = 525 // Acceptance threshold side D for CCD 9
CCD_9_UPPER_THR_C = 3600 // Upper threshold side C for CCD 9
CCD_9_UPPER_THR_D = 3600 // Acceptance threshold side D for CCD 9
NUMBER_OF_SLOTS = 8 // Number of readout slots
CCD_INDEX_1 = 1 // CCD read out in the 1st slot
CCD_1_OCB = 3 // On-chip binning factor for the CCD read out in the 1st slot
CCD_1_NODES = 3 // Read-out nodes used fot the CCD read out in the 1st slot
CCD_1_REJECT_THR_C = 195 // Rejection threshold side C for the CCD read out in the 1st slot
CCD_1_REJECT_THR_D = 190 // Rejection threshold side D for the CCD read out in the 1st slot
CCD_1_CSG_PATTERN = 6 // CCD read out in the 1st slot
CCD_INDEX_2 = 2 // CCD read out in the 2nd slot
CCD_2_OCB = 3 // On-chip binning factor for the CCD read out in the 2nd slot
CCD_2_NODES = 3 // Read-out nodes used fot the CCD read out in the 2nd slot
CCD_2_REJECT_THR_C = 190 // Rejection threshold side C for the CCD read out in the 2nd slot
CCD_2_REJECT_THR_D = 195 // Rejection threshold side D for the CCD read out in the 2nd slot
CCD_2_CSG_PATTERN = 7 // CCD read out in the 2nd slot
CCD_INDEX_3 = 3 // CCD read out in the 3rd slot
CCD_3_OCB = 3 // On-chip binning factor for the CCD read out in the 3rd slot
CCD_3_NODES = 3 // Read-out nodes used fot the CCD read out in the 3rd slot
CCD_3_REJECT_THR_C = 190 // Rejection threshold side C for the CCD read out in the 3rd slot
CCD_3_REJECT_THR_D = 185 // Rejection threshold side D for the CCD read out in the 3rd slot
CCD_3_CSG_PATTERN = 6 // CCD read out in the 3rd slot
CCD_INDEX_4 = 5 // CCD read out in the 4th slot
CCD_4_OCB = 3 // On-chip binning factor for the CCD read out in the 4th slot
CCD_4_NODES = 3 // Read-out nodes used fot the CCD read out in the 4th slot
CCD_4_REJECT_THR_C = 190 // Rejection threshold side C for the CCD read out in the 4th slot
CCD_4_REJECT_THR_D = 200 // Rejection threshold side D for the CCD read out in the 4th slot
CCD_4_CSG_PATTERN = 7 // CCD read out in the 4th slot
CCD_INDEX_5 = 6 // CCD read out in the 5th slot
CCD_5_OCB = 3 // On-chip binning factor for the CCD read out in the 5th slot
CCD_5_NODES = 3 // Read-out nodes used fot the CCD read out in the 5th slot
CCD_5_REJECT_THR_C = 190 // Rejection threshold side C for the CCD read out in the 5th slot
CCD_5_REJECT_THR_D = 190 // Rejection threshold side D for the CCD read out in the 5th slot
CCD_5_CSG_PATTERN = 7 // CCD read out in the 5th slot
CCD_INDEX_6 = 7 // CCD read out in the 6th slot
CCD_6_OCB = 3 // On-chip binning factor for the CCD read out in the 6th slot
CCD_6_NODES = 3 // Read-out nodes used fot the CCD read out in the 6th slot
CCD_6_REJECT_THR_C = 190 // Rejection threshold side C for the CCD read out in the 6th slot
CCD_6_REJECT_THR_D = 200 // Rejection threshold side D for the CCD read out in the 6th slot
CCD_6_CSG_PATTERN = 7 // CCD read out in the 6th slot
CCD_INDEX_7 = 8 // CCD read out in the 7th slot
CCD_7_OCB = 3 // On-chip binning factor for the CCD read out in the 7th slot
CCD_7_NODES = 3 // Read-out nodes used fot the CCD read out in the 7th slot
CCD_7_REJECT_THR_C = 185 // Rejection threshold side C for the CCD read out in the 7th slot
CCD_7_REJECT_THR_D = 200 // Rejection threshold side D for the CCD read out in the 7th slot
CCD_7_CSG_PATTERN = 7 // CCD read out in the 7th slot
CCD_INDEX_8 = 9 // CCD read out in the 8th slot
CCD_8_OCB = 3 // On-chip binning factor for the CCD read out in the 8th slot
CCD_8_NODES = 3 // Read-out nodes used fot the CCD read out in the 8th slot
CCD_8_REJECT_THR_C = 205 // Rejection threshold side C for the CCD read out in the 8th slot
CCD_8_REJECT_THR_D = 200 // Rejection threshold side D for the CCD read out in the 8th slot
CCD_8_CSG_PATTERN = 7 // CCD read out in the 8th slot
CCD_INDEX_9 = 0 // CCD read out in the 9th slot
CCD_9_OCB = 3 // On-chip binning factor for the CCD read out in the 9th slot
CCD_9_NODES = 3 // Read-out nodes used fot the CCD read out in the 9th slot
CCD_9_REJECT_THR_C = 0 // Rejection threshold side C for the CCD read out in the 9th slot
CCD_9_REJECT_THR_D = 0 // Rejection threshold side D for the CCD read out in the 9th slot
CCD_9_CSG_PATTERN = 0 // CCD read out in the 9th slot
CCD_INDEX_10 = 0 // CCD read out in the 10th slot
CCD_10_OCB = 3 // On-chip binning factor for the CCD read out in the 10th slot
CCD_10_NODES = 3 // Read-out nodes used fot the CCD read out in the 10th slot
CCD_10_REJECT_THR_C = 0 // Rejection threshold side C for the CCD read out in the 10th slot
CCD_10_REJECT_THR_D = 0 // Rejection threshold side D for the CCD read out in the 10th slot
CCD_10_CSG_PATTERN = 0 // CCD read out in the 10th slot
CCD_INDEX_11 = 0 // CCD read out in the 11th slot
CCD_11_OCB = 3 // On-chip binning factor for the CCD read out in the 11th slot
CCD_11_NODES = 3 // Read-out nodes used fot the CCD read out in the 11th slot
CCD_11_REJECT_THR_C = 0 // Rejection threshold side C for the CCD read out in the 11th slot
CCD_11_REJECT_THR_D = 0 // Rejection threshold side D for the CCD read out in the 11th slot
CCD_11_CSG_PATTERN = 0 // CCD read out in the 11th slot
CCD_INDEX_12 = 0 // CCD read out in the 12th slot
CCD_12_OCB = 3 // On-chip binning factor for the CCD read out in the 12th slot
CCD_12_NODES = 3 // Read-out nodes used fot the CCD read out in the 12th slot
CCD_12_REJECT_THR_C = 0 // Rejection threshold side C for the CCD read out in the 12th slot
CCD_12_REJECT_THR_D = 0 // Rejection threshold side D for the CCD read out in the 12th slot
CCD_12_CSG_PATTERN = 0 // CCD read out in the 12th slot
//
// Exposure Record
// Observation Level Exposure Index = 8
// Instrument [R2] Level Exposure Identifier = S901
// Instrument [R2] Level Exposure Index = 3
//
EXPOSURE
901 / Exposure Identifier [also S901]
Y / Is this a scheduled exposure?
SCIENCE / Exposure Type
0201901401R2S901 / Commanded Exposure Identifier
0201901401R2S901 / Proposal Exposure Identifier
2004-05-09T13:34:21.000 / Scheduled Start Time
2004-05-09T13:34:22.000 / Scheduled End Time
2004-05-09T13:34:21.000 / Actual Start Time
2004-05-09T13:34:22.000 / Actual End Time
//
// Configuration Record for R2
//
CONFIGURATION RGS
113 / Number of configuration parameters available
MODE = Diagnostic3x3 / Instrument configuration 
CALIBRATION_MODE_5 = Diagnostic3x3 / Mode used to calibrate events from CCD 5
DATA_MODE_5 = Diagnostic / Data mode for CCD 5
PACKING_SCHEME = PACKED // Packing scheme
CCD_1_ACCEPT_THR_C = 220 // Acceptance threshold side C for CCD 1
CCD_1_ACCEPT_THR_D = 215 // Acceptance threshold side D for CCD 1
CCD_1_UPPER_THR_C = 2600 // Upper threshold side C for CCD 1
CCD_1_UPPER_THR_D = 2600 // Acceptance threshold side D for CCD 1
CCD_2_ACCEPT_THR_C = 220 // Acceptance threshold side C for CCD 2
CCD_2_ACCEPT_THR_D = 245 // Acceptance threshold side D for CCD 2
CCD_2_UPPER_THR_C = 2600 // Upper threshold side C for CCD 2
CCD_2_UPPER_THR_D = 2600 // Acceptance threshold side D for CCD 2
CCD_3_ACCEPT_THR_C = 240 // Acceptance threshold side C for CCD 3
CCD_3_ACCEPT_THR_D = 265 // Acceptance threshold side D for CCD 3
CCD_3_UPPER_THR_C = 3100 // Upper threshold side C for CCD 3
CCD_3_UPPER_THR_D = 3100 // Acceptance threshold side D for CCD 3
CCD_4_ACCEPT_THR_C = 270 // Acceptance threshold side C for CCD 4
CCD_4_ACCEPT_THR_D = 305 // Acceptance threshold side D for CCD 4
CCD_4_UPPER_THR_C = 3100 // Upper threshold side C for CCD 4
CCD_4_UPPER_THR_D = 3100 // Acceptance threshold side D for CCD 4
CCD_5_ACCEPT_THR_C = 300 // Acceptance threshold side C for CCD 5
CCD_5_ACCEPT_THR_D = 325 // Acceptance threshold side D for CCD 5
CCD_5_UPPER_THR_C = 3100 // Upper threshold side C for CCD 5
CCD_5_UPPER_THR_D = 3100 // Acceptance threshold side D for CCD 5
CCD_6_ACCEPT_THR_C = 350 // Acceptance threshold side C for CCD 6
CCD_6_ACCEPT_THR_D = 375 // Acceptance threshold side D for CCD 6
CCD_6_UPPER_THR_C = 3100 // Upper threshold side C for CCD 6
CCD_6_UPPER_THR_D = 3100 // Acceptance threshold side D for CCD 6
CCD_7_ACCEPT_THR_C = 375 // Acceptance threshold side C for CCD 7
CCD_7_ACCEPT_THR_D = 325 // Acceptance threshold side D for CCD 7
CCD_7_UPPER_THR_C = 3600 // Upper threshold side C for CCD 7
CCD_7_UPPER_THR_D = 3600 // Acceptance threshold side D for CCD 7
CCD_8_ACCEPT_THR_C = 300 // Acceptance threshold side C for CCD 8
CCD_8_ACCEPT_THR_D = 500 // Acceptance threshold side D for CCD 8
CCD_8_UPPER_THR_C = 3600 // Upper threshold side C for CCD 8
CCD_8_UPPER_THR_D = 3600 // Acceptance threshold side D for CCD 8
CCD_9_ACCEPT_THR_C = 600 // Acceptance threshold side C for CCD 9
CCD_9_ACCEPT_THR_D = 525 // Acceptance threshold side D for CCD 9
CCD_9_UPPER_THR_C = 3600 // Upper threshold side C for CCD 9
CCD_9_UPPER_THR_D = 3600 // Acceptance threshold side D for CCD 9
NUMBER_OF_SLOTS = 8 // Number of readout slots
CCD_INDEX_1 = 1 // CCD read out in the 1st slot
CCD_1_OCB = 3 // On-chip binning factor for the CCD read out in the 1st slot
CCD_1_NODES = 3 // Read-out nodes used fot the CCD read out in the 1st slot
CCD_1_REJECT_THR_C = 195 // Rejection threshold side C for the CCD read out in the 1st slot
CCD_1_REJECT_THR_D = 190 // Rejection threshold side D for the CCD read out in the 1st slot
CCD_1_CSG_PATTERN = 6 // CCD read out in the 1st slot
CCD_INDEX_2 = 2 // CCD read out in the 2nd slot
CCD_2_OCB = 3 // On-chip binning factor for the CCD read out in the 2nd slot
CCD_2_NODES = 3 // Read-out nodes used fot the CCD read out in the 2nd slot
CCD_2_REJECT_THR_C = 190 // Rejection threshold side C for the CCD read out in the 2nd slot
CCD_2_REJECT_THR_D = 195 // Rejection threshold side D for the CCD read out in the 2nd slot
CCD_2_CSG_PATTERN = 7 // CCD read out in the 2nd slot
CCD_INDEX_3 = 3 // CCD read out in the 3rd slot
CCD_3_OCB = 3 // On-chip binning factor for the CCD read out in the 3rd slot
CCD_3_NODES = 3 // Read-out nodes used fot the CCD read out in the 3rd slot
CCD_3_REJECT_THR_C = 190 // Rejection threshold side C for the CCD read out in the 3rd slot
CCD_3_REJECT_THR_D = 185 // Rejection threshold side D for the CCD read out in the 3rd slot
CCD_3_CSG_PATTERN = 6 // CCD read out in the 3rd slot
CCD_INDEX_4 = 5 // CCD read out in the 4th slot
CCD_4_OCB = 3 // On-chip binning factor for the CCD read out in the 4th slot
CCD_4_NODES = 3 // Read-out nodes used fot the CCD read out in the 4th slot
CCD_4_REJECT_THR_C = 190 // Rejection threshold side C for the CCD read out in the 4th slot
CCD_4_REJECT_THR_D = 200 // Rejection threshold side D for the CCD read out in the 4th slot
CCD_4_CSG_PATTERN = 7 // CCD read out in the 4th slot
CCD_INDEX_5 = 6 // CCD read out in the 5th slot
CCD_5_OCB = 3 // On-chip binning factor for the CCD read out in the 5th slot
CCD_5_NODES = 3 // Read-out nodes used fot the CCD read out in the 5th slot
CCD_5_REJECT_THR_C = 190 // Rejection threshold side C for the CCD read out in the 5th slot
CCD_5_REJECT_THR_D = 190 // Rejection threshold side D for the CCD read out in the 5th slot
CCD_5_CSG_PATTERN = 7 // CCD read out in the 5th slot
CCD_INDEX_6 = 7 // CCD read out in the 6th slot
CCD_6_OCB = 3 // On-chip binning factor for the CCD read out in the 6th slot
CCD_6_NODES = 3 // Read-out nodes used fot the CCD read out in the 6th slot
CCD_6_REJECT_THR_C = 190 // Rejection threshold side C for the CCD read out in the 6th slot
CCD_6_REJECT_THR_D = 200 // Rejection threshold side D for the CCD read out in the 6th slot
CCD_6_CSG_PATTERN = 7 // CCD read out in the 6th slot
CCD_INDEX_7 = 8 // CCD read out in the 7th slot
CCD_7_OCB = 3 // On-chip binning factor for the CCD read out in the 7th slot
CCD_7_NODES = 3 // Read-out nodes used fot the CCD read out in the 7th slot
CCD_7_REJECT_THR_C = 185 // Rejection threshold side C for the CCD read out in the 7th slot
CCD_7_REJECT_THR_D = 200 // Rejection threshold side D for the CCD read out in the 7th slot
CCD_7_CSG_PATTERN = 7 // CCD read out in the 7th slot
CCD_INDEX_8 = 9 // CCD read out in the 8th slot
CCD_8_OCB = 3 // On-chip binning factor for the CCD read out in the 8th slot
CCD_8_NODES = 3 // Read-out nodes used fot the CCD read out in the 8th slot
CCD_8_REJECT_THR_C = 205 // Rejection threshold side C for the CCD read out in the 8th slot
CCD_8_REJECT_THR_D = 200 // Rejection threshold side D for the CCD read out in the 8th slot
CCD_8_CSG_PATTERN = 7 // CCD read out in the 8th slot
CCD_INDEX_9 = 0 // CCD read out in the 9th slot
CCD_9_OCB = 3 // On-chip binning factor for the CCD read out in the 9th slot
CCD_9_NODES = 3 // Read-out nodes used fot the CCD read out in the 9th slot
CCD_9_REJECT_THR_C = 0 // Rejection threshold side C for the CCD read out in the 9th slot
CCD_9_REJECT_THR_D = 0 // Rejection threshold side D for the CCD read out in the 9th slot
CCD_9_CSG_PATTERN = 0 // CCD read out in the 9th slot
CCD_INDEX_10 = 0 // CCD read out in the 10th slot
CCD_10_OCB = 3 // On-chip binning factor for the CCD read out in the 10th slot
CCD_10_NODES = 3 // Read-out nodes used fot the CCD read out in the 10th slot
CCD_10_REJECT_THR_C = 0 // Rejection threshold side C for the CCD read out in the 10th slot
CCD_10_REJECT_THR_D = 0 // Rejection threshold side D for the CCD read out in the 10th slot
CCD_10_CSG_PATTERN = 0 // CCD read out in the 10th slot
CCD_INDEX_11 = 0 // CCD read out in the 11th slot
CCD_11_OCB = 3 // On-chip binning factor for the CCD read out in the 11th slot
CCD_11_NODES = 3 // Read-out nodes used fot the CCD read out in the 11th slot
CCD_11_REJECT_THR_C = 0 // Rejection threshold side C for the CCD read out in the 11th slot
CCD_11_REJECT_THR_D = 0 // Rejection threshold side D for the CCD read out in the 11th slot
CCD_11_CSG_PATTERN = 0 // CCD read out in the 11th slot
CCD_INDEX_12 = 0 // CCD read out in the 12th slot
CCD_12_OCB = 3 // On-chip binning factor for the CCD read out in the 12th slot
CCD_12_NODES = 3 // Read-out nodes used fot the CCD read out in the 12th slot
CCD_12_REJECT_THR_C = 0 // Rejection threshold side C for the CCD read out in the 12th slot
CCD_12_REJECT_THR_D = 0 // Rejection threshold side D for the CCD read out in the 12th slot
CCD_12_CSG_PATTERN = 0 // CCD read out in the 12th slot
//
// Instrument Record
//
INSTRUMENT
PN
Y / Is this instrument active?
13 / Number of exposures for this instrument
//
// Exposure Record
// Observation Level Exposure Index = 9
// Instrument [PN] Level Exposure Identifier = U002
// Instrument [PN] Level Exposure Index = 1
//
EXPOSURE
002 / Exposure Identifier [also U002]
N / Is this a scheduled exposure?
SCIENCE / Exposure Type
0201901401PNU002 / Commanded Exposure Identifier
0201901401PNU002 / Proposal Exposure Identifier
2004-05-09T16:50:54.000 / Scheduled Start Time
2004-05-09T20:11:25.000 / Scheduled End Time
2004-05-09T16:50:54.000 / Actual Start Time
2004-05-09T20:11:25.000 / Actual End Time
//
// Configuration Record for PN
//
CONFIGURATION EPIC PN
70 / Number of configuration parameters available
MODE = PrimeFullWindowExtended / Instrument configuration 
CALIBRATION_MODE_1 = PrimeFullWindow / Mode used to calibrate events from CCD 1
CALIBRATION_MODE_2 = PrimeFullWindow / Mode used to calibrate events from CCD 2
CALIBRATION_MODE_3 = PrimeFullWindow / Mode used to calibrate events from CCD 3
CALIBRATION_MODE_4 = PrimeFullWindow / Mode used to calibrate events from CCD 4
CALIBRATION_MODE_5 = PrimeFullWindow / Mode used to calibrate events from CCD 5
CALIBRATION_MODE_6 = PrimeFullWindow / Mode used to calibrate events from CCD 6
CALIBRATION_MODE_7 = PrimeFullWindow / Mode used to calibrate events from CCD 7
CALIBRATION_MODE_8 = PrimeFullWindow / Mode used to calibrate events from CCD 8
CALIBRATION_MODE_9 = PrimeFullWindow / Mode used to calibrate events from CCD 9
CALIBRATION_MODE_10 = PrimeFullWindow / Mode used to calibrate events from CCD 10
CALIBRATION_MODE_11 = PrimeFullWindow / Mode used to calibrate events from CCD 11
CALIBRATION_MODE_12 = PrimeFullWindow / Mode used to calibrate events from CCD 12
DATA_MODE_1 = Imaging / Data mode for CCD 1
DATA_MODE_2 = Imaging / Data mode for CCD 2
DATA_MODE_3 = Imaging / Data mode for CCD 3
DATA_MODE_4 = Imaging / Data mode for CCD 4
DATA_MODE_5 = Imaging / Data mode for CCD 5
DATA_MODE_6 = Imaging / Data mode for CCD 6
DATA_MODE_7 = Imaging / Data mode for CCD 7
DATA_MODE_8 = Imaging / Data mode for CCD 8
DATA_MODE_9 = Imaging / Data mode for CCD 9
DATA_MODE_10 = Imaging / Data mode for CCD 10
DATA_MODE_11 = Imaging / Data mode for CCD 11
DATA_MODE_12 = Imaging / Data mode for CCD 12
HBR_0_ACTIVATION_STATUS = 1 // Activation status for HBR 0
HBR_1_ACTIVATION_STATUS = 1 // Activation status for HBR 1
HBR_2_ACTIVATION_STATUS = 1 // Activation status for HBR 2
HBR_3_ACTIVATION_STATUS = 0 // Activation status for HBR 3
FILTER = Thin1 // Filter position translated from potentiometer readout
FILTER_WHEEL_POSITION = 114.74 // Hardware filter wheel position
FRAME_TIME_PARAMETER = 3 // 
CLOCK_RESET_TIME_COARSE = 121747009 // Coarse component of the clock reset time
CLOCK_RESET_TIME_FINE = 0 // Fine component of the clock reset time
CLOCK_WRAP_AROUND = 32400 // Clock wrap around
CAMEX_GAIN_CCD1 = HIGH // 
CAMEX_GAIN_CCD2 = HIGH // 
CAMEX_GAIN_CCD3 = HIGH // 
CAMEX_GAIN_CCD4 = HIGH // 
CAMEX_GAIN_CCD5 = HIGH // 
CAMEX_GAIN_CCD6 = HIGH // 
CAMEX_GAIN_CCD7 = HIGH // 
CAMEX_GAIN_CCD8 = HIGH // 
CAMEX_GAIN_CCD9 = HIGH // 
CAMEX_GAIN_CCD10 = HIGH // 
CAMEX_GAIN_CCD11 = HIGH // 
CAMEX_GAIN_CCD12 = HIGH // 
LOWER_THRESHOLD_Q0_CCD0 = 532 // 
LOWER_THRESHOLD_Q0_CCD1 = 532 // 
LOWER_THRESHOLD_Q0_CCD2 = 532 // 
LOWER_THRESHOLD_Q1_CCD0 = 532 // 
LOWER_THRESHOLD_Q1_CCD1 = 532 // 
LOWER_THRESHOLD_Q1_CCD2 = 532 // 
LOWER_THRESHOLD_Q2_CCD0 = 532 // 
LOWER_THRESHOLD_Q2_CCD1 = 532 // 
LOWER_THRESHOLD_Q2_CCD2 = 532 // 
LOWER_THRESHOLD_Q3_CCD0 = 532 // 
LOWER_THRESHOLD_Q3_CCD1 = 532 // 
LOWER_THRESHOLD_Q3_CCD2 = 532 // 
CMCORR_Q0 = 512 // 
CMCORR_Q1 = 512 // 
CMCORR_Q2 = 512 // 
CMCORR_Q3 = 512 // 
QUADRANT_UNDERSAMPLING_Q0 = 0 // 
QUADRANT_UNDERSAMPLING_Q1 = 0 // 
QUADRANT_UNDERSAMPLING_Q2 = 0 // 
QUADRANT_UNDERSAMPLING_Q3 = 0 // 
A1_CMLINE_PIXSET = BAD // 
A1_CMLINE_CCD = 0 // 
A1_CMLINE_NUMB = 1 // 
//
// Exposure Record
// Observation Level Exposure Index = 10
// Instrument [PN] Level Exposure Identifier = U003
// Instrument [PN] Level Exposure Index = 2
//
EXPOSURE
003 / Exposure Identifier [also U003]
N / Is this a scheduled exposure?
SCIENCE / Exposure Type
0201901401PNU003 / Commanded Exposure Identifier
0201901401PNU003 / Proposal Exposure Identifier
2004-05-09T20:14:54.000 / Scheduled Start Time
2004-05-09T20:14:55.000 / Scheduled End Time
2004-05-09T20:14:54.000 / Actual Start Time
2004-05-09T20:14:55.000 / Actual End Time
//
// Configuration Record for PN
//
CONFIGURATION EPIC PN
3 / Number of configuration parameters available
MODE = Diagnostic / Instrument configuration 
CALIBRATION_MODE_1 = Diagnostic / Mode used to calibrate events from CCD 1
DATA_MODE_1 = DiscardedLinesData / Data mode for CCD 1
//
// Exposure Record
// Observation Level Exposure Index = 11
// Instrument [PN] Level Exposure Identifier = U004
// Instrument [PN] Level Exposure Index = 3
//
EXPOSURE
004 / Exposure Identifier [also U004]
N / Is this a scheduled exposure?
SCIENCE / Exposure Type
0201901401PNU004 / Commanded Exposure Identifier
0201901401PNU004 / Proposal Exposure Identifier
2004-05-09T20:15:16.000 / Scheduled Start Time
2004-05-09T20:15:17.000 / Scheduled End Time
2004-05-09T20:15:16.000 / Actual Start Time
2004-05-09T20:15:17.000 / Actual End Time
//
// Configuration Record for PN
//
CONFIGURATION EPIC PN
3 / Number of configuration parameters available
MODE = Diagnostic / Instrument configuration 
CALIBRATION_MODE_2 = Diagnostic / Mode used to calibrate events from CCD 2
DATA_MODE_2 = DiscardedLinesData / Data mode for CCD 2
//
// Exposure Record
// Observation Level Exposure Index = 12
// Instrument [PN] Level Exposure Identifier = U005
// Instrument [PN] Level Exposure Index = 4
//
EXPOSURE
005 / Exposure Identifier [also U005]
N / Is this a scheduled exposure?
SCIENCE / Exposure Type
0201901401PNU005 / Commanded Exposure Identifier
0201901401PNU005 / Proposal Exposure Identifier
2004-05-09T20:15:34.000 / Scheduled Start Time
2004-05-09T20:15:35.000 / Scheduled End Time
2004-05-09T20:15:34.000 / Actual Start Time
2004-05-09T20:15:35.000 / Actual End Time
//
// Configuration Record for PN
//
CONFIGURATION EPIC PN
3 / Number of configuration parameters available
MODE = Diagnostic / Instrument configuration 
CALIBRATION_MODE_3 = Diagnostic / Mode used to calibrate events from CCD 3
DATA_MODE_3 = DiscardedLinesData / Data mode for CCD 3
//
// Exposure Record
// Observation Level Exposure Index = 13
// Instrument [PN] Level Exposure Identifier = U006
// Instrument [PN] Level Exposure Index = 5
//
EXPOSURE
006 / Exposure Identifier [also U006]
N / Is this a scheduled exposure?
SCIENCE / Exposure Type
0201901401PNU006 / Commanded Exposure Identifier
0201901401PNU006 / Proposal Exposure Identifier
2004-05-09T20:15:58.000 / Scheduled Start Time
2004-05-09T20:15:59.000 / Scheduled End Time
2004-05-09T20:15:58.000 / Actual Start Time
2004-05-09T20:15:59.000 / Actual End Time
//
// Configuration Record for PN
//
CONFIGURATION EPIC PN
3 / Number of configuration parameters available
MODE = Diagnostic / Instrument configuration 
CALIBRATION_MODE_4 = Diagnostic / Mode used to calibrate events from CCD 4
DATA_MODE_4 = DiscardedLinesData / Data mode for CCD 4
//
// Exposure Record
// Observation Level Exposure Index = 14
// Instrument [PN] Level Exposure Identifier = U007
// Instrument [PN] Level Exposure Index = 6
//
EXPOSURE
007 / Exposure Identifier [also U007]
N / Is this a scheduled exposure?
SCIENCE / Exposure Type
0201901401PNU007 / Commanded Exposure Identifier
0201901401PNU007 / Proposal Exposure Identifier
2004-05-09T20:16:22.000 / Scheduled Start Time
2004-05-09T20:16:23.000 / Scheduled End Time
2004-05-09T20:16:22.000 / Actual Start Time
2004-05-09T20:16:23.000 / Actual End Time
//
// Configuration Record for PN
//
CONFIGURATION EPIC PN
3 / Number of configuration parameters available
MODE = Diagnostic / Instrument configuration 
CALIBRATION_MODE_5 = Diagnostic / Mode used to calibrate events from CCD 5
DATA_MODE_5 = DiscardedLinesData / Data mode for CCD 5
//
// Exposure Record
// Observation Level Exposure Index = 15
// Instrument [PN] Level Exposure Identifier = U008
// Instrument [PN] Level Exposure Index = 7
//
EXPOSURE
008 / Exposure Identifier [also U008]
N / Is this a scheduled exposure?
SCIENCE / Exposure Type
0201901401PNU008 / Commanded Exposure Identifier
0201901401PNU008 / Proposal Exposure Identifier
2004-05-09T20:16:40.000 / Scheduled Start Time
2004-05-09T20:16:41.000 / Scheduled End Time
2004-05-09T20:16:40.000 / Actual Start Time
2004-05-09T20:16:41.000 / Actual End Time
//
// Configuration Record for PN
//
CONFIGURATION EPIC PN
3 / Number of configuration parameters available
MODE = Diagnostic / Instrument configuration 
CALIBRATION_MODE_6 = Diagnostic / Mode used to calibrate events from CCD 6
DATA_MODE_6 = DiscardedLinesData / Data mode for CCD 6
//
// Exposure Record
// Observation Level Exposure Index = 16
// Instrument [PN] Level Exposure Identifier = U009
// Instrument [PN] Level Exposure Index = 8
//
EXPOSURE
009 / Exposure Identifier [also U009]
N / Is this a scheduled exposure?
SCIENCE / Exposure Type
0201901401PNU009 / Commanded Exposure Identifier
0201901401PNU009 / Proposal Exposure Identifier
2004-05-09T20:17:04.000 / Scheduled Start Time
2004-05-09T20:17:05.000 / Scheduled End Time
2004-05-09T20:17:04.000 / Actual Start Time
2004-05-09T20:17:05.000 / Actual End Time
//
// Configuration Record for PN
//
CONFIGURATION EPIC PN
3 / Number of configuration parameters available
MODE = Diagnostic / Instrument configuration 
CALIBRATION_MODE_7 = Diagnostic / Mode used to calibrate events from CCD 7
DATA_MODE_7 = DiscardedLinesData / Data mode for CCD 7
//
// Exposure Record
// Observation Level Exposure Index = 17
// Instrument [PN] Level Exposure Identifier = U010
// Instrument [PN] Level Exposure Index = 9
//
EXPOSURE
010 / Exposure Identifier [also U010]
N / Is this a scheduled exposure?
SCIENCE / Exposure Type
0201901401PNU010 / Commanded Exposure Identifier
0201901401PNU010 / Proposal Exposure Identifier
2004-05-09T20:17:28.000 / Scheduled Start Time
2004-05-09T20:17:29.000 / Scheduled End Time
2004-05-09T20:17:28.000 / Actual Start Time
2004-05-09T20:17:29.000 / Actual End Time
//
// Configuration Record for PN
//
CONFIGURATION EPIC PN
3 / Number of configuration parameters available
MODE = Diagnostic / Instrument configuration 
CALIBRATION_MODE_8 = Diagnostic / Mode used to calibrate events from CCD 8
DATA_MODE_8 = DiscardedLinesData / Data mode for CCD 8
//
// Exposure Record
// Observation Level Exposure Index = 18
// Instrument [PN] Level Exposure Identifier = U011
// Instrument [PN] Level Exposure Index = 10
//
EXPOSURE
011 / Exposure Identifier [also U011]
N / Is this a scheduled exposure?
SCIENCE / Exposure Type
0201901401PNU011 / Commanded Exposure Identifier
0201901401PNU011 / Proposal Exposure Identifier
2004-05-09T20:17:45.000 / Scheduled Start Time
2004-05-09T20:17:46.000 / Scheduled End Time
2004-05-09T20:17:45.000 / Actual Start Time
2004-05-09T20:17:46.000 / Actual End Time
//
// Configuration Record for PN
//
CONFIGURATION EPIC PN
3 / Number of configuration parameters available
MODE = Diagnostic / Instrument configuration 
CALIBRATION_MODE_9 = Diagnostic / Mode used to calibrate events from CCD 9
DATA_MODE_9 = DiscardedLinesData / Data mode for CCD 9
//
// Exposure Record
// Observation Level Exposure Index = 19
// Instrument [PN] Level Exposure Identifier = U012
// Instrument [PN] Level Exposure Index = 11
//
EXPOSURE
012 / Exposure Identifier [also U012]
N / Is this a scheduled exposure?
SCIENCE / Exposure Type
0201901401PNU012 / Commanded Exposure Identifier
0201901401PNU012 / Proposal Exposure Identifier
2004-05-09T20:18:10.000 / Scheduled Start Time
2004-05-09T20:18:11.000 / Scheduled End Time
2004-05-09T20:18:10.000 / Actual Start Time
2004-05-09T20:18:11.000 / Actual End Time
//
// Configuration Record for PN
//
CONFIGURATION EPIC PN
3 / Number of configuration parameters available
MODE = Diagnostic / Instrument configuration 
CALIBRATION_MODE_10 = Diagnostic / Mode used to calibrate events from CCD 10
DATA_MODE_10 = DiscardedLinesData / Data mode for CCD 10
//
// Exposure Record
// Observation Level Exposure Index = 20
// Instrument [PN] Level Exposure Identifier = U013
// Instrument [PN] Level Exposure Index = 12
//
EXPOSURE
013 / Exposure Identifier [also U013]
N / Is this a scheduled exposure?
SCIENCE / Exposure Type
0201901401PNU013 / Commanded Exposure Identifier
0201901401PNU013 / Proposal Exposure Identifier
2004-05-09T20:18:31.000 / Scheduled Start Time
2004-05-09T20:18:32.000 / Scheduled End Time
2004-05-09T20:18:31.000 / Actual Start Time
2004-05-09T20:18:32.000 / Actual End Time
//
// Configuration Record for PN
//
CONFIGURATION EPIC PN
3 / Number of configuration parameters available
MODE = Diagnostic / Instrument configuration 
CALIBRATION_MODE_11 = Diagnostic / Mode used to calibrate events from CCD 11
DATA_MODE_11 = DiscardedLinesData / Data mode for CCD 11
//
// Exposure Record
// Observation Level Exposure Index = 21
// Instrument [PN] Level Exposure Identifier = U014
// Instrument [PN] Level Exposure Index = 13
//
EXPOSURE
014 / Exposure Identifier [also U014]
N / Is this a scheduled exposure?
SCIENCE / Exposure Type
0201901401PNU014 / Commanded Exposure Identifier
0201901401PNU014 / Proposal Exposure Identifier
2004-05-09T20:18:49.000 / Scheduled Start Time
2004-05-09T20:18:50.000 / Scheduled End Time
2004-05-09T20:18:49.000 / Actual Start Time
2004-05-09T20:18:50.000 / Actual End Time
//
// Configuration Record for PN
//
CONFIGURATION EPIC PN
3 / Number of configuration parameters available
MODE = Diagnostic / Instrument configuration 
CALIBRATION_MODE_12 = Diagnostic / Mode used to calibrate events from CCD 12
DATA_MODE_12 = DiscardedLinesData / Data mode for CCD 12
//
// Instrument Record
//
INSTRUMENT
OM
Y / Is this instrument active?
8 / Number of exposures for this instrument
//
// Exposure Record
// Observation Level Exposure Index = 22
// Instrument [OM] Level Exposure Identifier = S006
// Instrument [OM] Level Exposure Index = 1
//
EXPOSURE
006 / Exposure Identifier [also S006]
Y / Is this a scheduled exposure?
SCIENCE / Exposure Type
0201901401OMS006 / Commanded Exposure Identifier
0201901401OMS006 / Proposal Exposure Identifier
2004-05-09T13:00:16.000 / Scheduled Start Time
2004-05-09T13:36:56.000 / Scheduled End Time
2004-05-09T13:00:16.000 / Actual Start Time
2004-05-09T13:36:56.000 / Actual End Time
//
// Configuration Record for OM
//
CONFIGURATION OM
9 / Number of configuration parameters available
MODE = Image / Instrument configuration 
CALIBRATION_MODE_0 = Image / Mode used to calibrate events from window 0
CALIBRATION_MODE_1 = Image / Mode used to calibrate events from window 1
DATA_MODE_0 = Imaging / Data mode for window 0
DATA_MODE_1 = Imaging / Data mode for window 1
EXPOSURE_DURATION = 110 // 
FILTER_WHEEL_POSITION = 400 // Hardware filter wheel position
FILTER = UVW1 // Filter
FLOOD_LED_BIAS = 0 // LED Status
//
// Exposure Record
// Observation Level Exposure Index = 23
// Instrument [OM] Level Exposure Identifier = S007
// Instrument [OM] Level Exposure Index = 2
//
EXPOSURE
007 / Exposure Identifier [also S007]
Y / Is this a scheduled exposure?
SCIENCE / Exposure Type
0201901401OMS007 / Commanded Exposure Identifier
0201901401OMS007 / Proposal Exposure Identifier
2004-05-09T16:30:23.000 / Scheduled Start Time
2004-05-09T17:11:43.000 / Scheduled End Time
2004-05-09T16:30:23.000 / Actual Start Time
2004-05-09T17:11:43.000 / Actual End Time
//
// Configuration Record for OM
//
CONFIGURATION OM
9 / Number of configuration parameters available
MODE = Image / Instrument configuration 
CALIBRATION_MODE_0 = Image / Mode used to calibrate events from window 0
CALIBRATION_MODE_1 = Image / Mode used to calibrate events from window 1
DATA_MODE_0 = Imaging / Data mode for window 0
DATA_MODE_1 = Imaging / Data mode for window 1
EXPOSURE_DURATION = 124 // 
FILTER_WHEEL_POSITION = 600 // Hardware filter wheel position
FILTER = UVM2 // Filter
FLOOD_LED_BIAS = 0 // LED Status
//
// Exposure Record
// Observation Level Exposure Index = 24
// Instrument [OM] Level Exposure Identifier = S400
// Instrument [OM] Level Exposure Index = 3
//
EXPOSURE
400 / Exposure Identifier [also S400]
Y / Is this a scheduled exposure?
SCIENCE / Exposure Type
0201901401OMS400 / Commanded Exposure Identifier
0201901401OMS400 / Proposal Exposure Identifier
2004-05-09T13:00:16.000 / Scheduled Start Time
2004-05-09T13:36:56.000 / Scheduled End Time
2004-05-09T13:00:16.000 / Actual Start Time
2004-05-09T13:36:56.000 / Actual End Time
//
// Configuration Record for OM
//
CONFIGURATION OM
5 / Number of configuration parameters available
MODE = UNDEFINED / Instrument configuration 
EXPOSURE_DURATION = 110 // 
FILTER_WHEEL_POSITION = 400 // Hardware filter wheel position
FILTER = UVW1 // Filter
FLOOD_LED_BIAS = 0 // LED Status
//
// Exposure Record
// Observation Level Exposure Index = 25
// Instrument [OM] Level Exposure Identifier = S404
// Instrument [OM] Level Exposure Index = 4
//
EXPOSURE
404 / Exposure Identifier [also S404]
Y / Is this a scheduled exposure?
SCIENCE / Exposure Type
0201901401OMS404 / Commanded Exposure Identifier
0201901401OMS404 / Proposal Exposure Identifier
2004-05-09T16:30:23.000 / Scheduled Start Time
2004-05-09T16:25:04.000 / Scheduled End Time
2004-05-09T16:30:23.000 / Actual Start Time
2004-05-09T16:25:04.000 / Actual End Time
//
// Configuration Record for OM
//
CONFIGURATION OM
9 / Number of configuration parameters available
MODE = Image / Instrument configuration 
CALIBRATION_MODE_0 = Image / Mode used to calibrate events from window 0
CALIBRATION_MODE_1 = Image / Mode used to calibrate events from window 1
DATA_MODE_0 = Imaging / Data mode for window 0
DATA_MODE_1 = Imaging / Data mode for window 1
EXPOSURE_DURATION = 124 // 
FILTER_WHEEL_POSITION = 600 // Hardware filter wheel position
FILTER = UVM2 // Filter
FLOOD_LED_BIAS = -nan // LED Status
//
// Exposure Record
// Observation Level Exposure Index = 26
// Instrument [OM] Level Exposure Identifier = S405
// Instrument [OM] Level Exposure Index = 5
//
EXPOSURE
405 / Exposure Identifier [also S405]
Y / Is this a scheduled exposure?
SCIENCE / Exposure Type
0201901401OMS405 / Commanded Exposure Identifier
0201901401OMS405 / Proposal Exposure Identifier
2004-05-09T17:17:08.000 / Scheduled Start Time
2004-05-09T17:58:27.000 / Scheduled End Time
2004-05-09T17:17:08.000 / Actual Start Time
2004-05-09T17:58:27.000 / Actual End Time
//
// Configuration Record for OM
//
CONFIGURATION OM
9 / Number of configuration parameters available
MODE = Image / Instrument configuration 
CALIBRATION_MODE_0 = Image / Mode used to calibrate events from window 0
CALIBRATION_MODE_1 = Image / Mode used to calibrate events from window 1
DATA_MODE_0 = Imaging / Data mode for window 0
DATA_MODE_1 = Imaging / Data mode for window 1
EXPOSURE_DURATION = 124 // 
FILTER_WHEEL_POSITION = 600 // Hardware filter wheel position
FILTER = UVM2 // Filter
FLOOD_LED_BIAS = 0 // LED Status
//
// Exposure Record
// Observation Level Exposure Index = 27
// Instrument [OM] Level Exposure Identifier = S406
// Instrument [OM] Level Exposure Index = 6
//
EXPOSURE
406 / Exposure Identifier [also S406]
Y / Is this a scheduled exposure?
SCIENCE / Exposure Type
0201901401OMS406 / Commanded Exposure Identifier
0201901401OMS406 / Proposal Exposure Identifier
2004-05-09T18:03:52.000 / Scheduled Start Time
2004-05-09T18:45:11.000 / Scheduled End Time
2004-05-09T18:03:52.000 / Actual Start Time
2004-05-09T18:45:11.000 / Actual End Time
//
// Configuration Record for OM
//
CONFIGURATION OM
9 / Number of configuration parameters available
MODE = Image / Instrument configuration 
CALIBRATION_MODE_0 = Image / Mode used to calibrate events from window 0
CALIBRATION_MODE_1 = Image / Mode used to calibrate events from window 1
DATA_MODE_0 = Imaging / Data mode for window 0
DATA_MODE_1 = Imaging / Data mode for window 1
EXPOSURE_DURATION = 124 // 
FILTER_WHEEL_POSITION = 600 // Hardware filter wheel position
FILTER = UVM2 // Filter
FLOOD_LED_BIAS = 0 // LED Status
//
// Exposure Record
// Observation Level Exposure Index = 28
// Instrument [OM] Level Exposure Identifier = S407
// Instrument [OM] Level Exposure Index = 7
//
EXPOSURE
407 / Exposure Identifier [also S407]
Y / Is this a scheduled exposure?
SCIENCE / Exposure Type
0201901401OMS407 / Commanded Exposure Identifier
0201901401OMS407 / Proposal Exposure Identifier
2004-05-09T18:50:35.000 / Scheduled Start Time
2004-05-09T19:31:55.000 / Scheduled End Time
2004-05-09T18:50:35.000 / Actual Start Time
2004-05-09T19:31:55.000 / Actual End Time
//
// Configuration Record for OM
//
CONFIGURATION OM
9 / Number of configuration parameters available
MODE = Image / Instrument configuration 
CALIBRATION_MODE_0 = Image / Mode used to calibrate events from window 0
CALIBRATION_MODE_1 = Image / Mode used to calibrate events from window 1
DATA_MODE_0 = Imaging / Data mode for window 0
DATA_MODE_1 = Imaging / Data mode for window 1
EXPOSURE_DURATION = 124 // 
FILTER_WHEEL_POSITION = 600 // Hardware filter wheel position
FILTER = UVM2 // Filter
FLOOD_LED_BIAS = 0 // LED Status
//
// Exposure Record
// Observation Level Exposure Index = 29
// Instrument [OM] Level Exposure Identifier = S408
// Instrument [OM] Level Exposure Index = 8
//
EXPOSURE
408 / Exposure Identifier [also S408]
Y / Is this a scheduled exposure?
SCIENCE / Exposure Type
0201901401OMS408 / Commanded Exposure Identifier
0201901401OMS408 / Proposal Exposure Identifier
2004-05-09T19:37:20.000 / Scheduled Start Time
2004-05-09T20:18:39.000 / Scheduled End Time
2004-05-09T19:37:20.000 / Actual Start Time
2004-05-09T20:18:39.000 / Actual End Time
//
// Configuration Record for OM
//
CONFIGURATION OM
9 / Number of configuration parameters available
MODE = Image / Instrument configuration 
CALIBRATION_MODE_0 = Image / Mode used to calibrate events from window 0
CALIBRATION_MODE_1 = Image / Mode used to calibrate events from window 1
DATA_MODE_0 = Imaging / Data mode for window 0
DATA_MODE_1 = Imaging / Data mode for window 1
EXPOSURE_DURATION = 124 // 
FILTER_WHEEL_POSITION = 600 // Hardware filter wheel position
FILTER = UVM2 // Filter
FLOOD_LED_BIAS = 0 // LED Status
// The PROPOSAL record was extracted from 0809_0201901401_SCX00000SUM.ASC
PROPOSAL                                                                        
Dr    HANS                BOEHRINGER                                            
MPE                                                                             
GIESSENBACHSTR.                                                                 
                                                                                
GARCHING                                                                        
                                                                                
GERMANY                                                                         
D-85748                                                                         
HXB@MPE.MPG.DE                                                                  
 3 / Announcement of Opportunity                                                
 G / Observation type                                                           
RXCJ0958.3-1103      / Target Name                                              
 9.9728195 / Target Right Ascension                                             
-11.0597000 / Target Declination                                                
 27350 / Proposed Observation Duration                                          
                                                                                
 9.9728195 / Boresight Right Ascension                                          
-11.0597000 / Boresight Declination                                             
  0 / Position Angle Constraint (Lower)                                         
360 / Position Angle Constraint (Upper)                                         
N / Position Angle Origin reference                                             
  / Epic MOS 1 priority                                                         
  / Epic MOS 2 priority                                                         
  / Epic pn priority                                                            
  / RGS 1 priority                                                              
  / RGS 2 priority                                                              
  / OM priority                                                                 
DATA QUALITY                                                                    
OM / Instrument Id                                                              
0201901401OM400 / Exposure Id                                                   
   0 / Number of packets that failed reception checking                         
   3 / Number of event reports                                                  
   0 / Number of PMS errors                                                     
   2 / Number of Telemetry drops                                                
   3 / Total duration of Telemetry drops                                        
   0 / Number of Telemetry out of limits                                        
S / Scheduled flag                                                              
DATA QUALITY                                                                    
OM / Instrument Id                                                              
0201901401OM006 / Exposure Id                                                   
   0 / Number of packets that failed reception checking                         
   7 / Number of event reports                                                  
   0 / Number of PMS errors                                                     
  16 / Number of Telemetry drops                                                
 133 / Total duration of Telemetry drops                                        
   0 / Number of Telemetry out of limits                                        
S / Scheduled flag                                                              
DATA QUALITY                                                                    
R1 / Instrument Id                                                              
0201901401R1902 / Exposure Id                                                   
   0 / Number of packets that failed reception checking                         
   0 / Number of event reports                                                  
   0 / Number of PMS errors                                                     
   8 / Number of Telemetry drops                                                
   6 / Total duration of Telemetry drops                                        
   0 / Number of Telemetry out of limits                                        
S / Scheduled flag                                                              
DATA QUALITY                                                                    
R2 / Instrument Id                                                              
0201901401R2920 / Exposure Id                                                   
   0 / Number of packets that failed reception checking                         
   0 / Number of event reports                                                  
   0 / Number of PMS errors                                                     
   9 / Number of Telemetry drops                                                
   4 / Total duration of Telemetry drops                                        
   0 / Number of Telemetry out of limits                                        
S / Scheduled flag                                                              
DATA QUALITY                                                                    
R1 / Instrument Id                                                              
0201901401R1903 / Exposure Id                                                   
   0 / Number of packets that failed reception checking                         
   0 / Number of event reports                                                  
   0 / Number of PMS errors                                                     
   7 / Number of Telemetry drops                                                
   4 / Total duration of Telemetry drops                                        
   0 / Number of Telemetry out of limits                                        
S / Scheduled flag                                                              
DATA QUALITY                                                                    
R2 / Instrument Id                                                              
0201901401R2921 / Exposure Id                                                   
   0 / Number of packets that failed reception checking                         
   0 / Number of event reports                                                  
   0 / Number of PMS errors                                                     
   5 / Number of Telemetry drops                                                
   3 / Total duration of Telemetry drops                                        
   0 / Number of Telemetry out of limits                                        
S / Scheduled flag                                                              

