# The overall name of this action
name: Compile draft XGA JOSS Paper

# Triggers on a push to the master branch - as I've decided that the paper can live in master
on:
  push:
    branches:
      - master
      - paper/writeJOSSPaper
    paths:
      - paper/**

# This action only really does one job, using the JOSS paper action to compile the MarkDown into something
#  slightly more pretty
jobs:
  paper:
    # Sets up the run on the latest version of Ubuntu they have 'in stock'
    runs-on: ubuntu-latest
    # Names the job
    name: Paper Draft
    # Sets up the steps of the job, firstly we check out the master branch
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        # Then use the JOSS action to build the paper
      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        # Sets the specific journal to be built for, and where the Markdown file lives
        with:
          journal: joss
          paper-path: paper/paper.md
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: paper
          # This is the output path where Pandoc will write the compiled PDF
          path: paper/paper.pdf