# Large parts of this are directly copied or adapted from 
#  https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

# This action triggers the second stage of publishing this module. When a new release is created this action will begin. It builds the module, then
#  publishes it to the real PyPI index


# The overall name of the action
name: Publish XGA to real PyPI, triggered on creation of release

# This action triggers when there is a release to the repo, but only when the release is published
on: 
  release:
      types: [published]

# Now the actual jobs we want the action to do are setup
jobs:
  # The only job in this action, building and publishing the XGA Python module
  build-n-publish:
    name: Build and publish XGA
    # The build/publishing process runs on Ubuntu 20.04 - not super important what this is for this use case, so long as its not Windows
    runs-on: ubuntu-20.04
    
    # This job has several steps
    steps:
      # Checks out the master branch (what we want to build and publish - hopefully with the VCS info that versioneer needs), then 
      #  activates a relatively recent version of Python
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup the Python install
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    
    # The next two chunks set up PIP properly and build the module
    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user

    - name: Install wheel
      run: >- 
        pip install wheel
    
#     - name: Build a binary wheel and source tarball
#       run: >-
#         python -m
#         build
#         --sdist
#         --wheel
#         --outdir dist/
#         .
    - name: Build a binary wheel and source tarball
      run: >-
        python3 setup.py sdist bdist_wheel
    
    # Then the module is published to the real PyPI index
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
